export const scenarios = [
  { id: "family_check_in", title: "Family Check In", task: "Call the recipient and complete the family check in task.", success: ["confirmed", "completed", "yes"], failure: ["no answer", "declined", "unknown"] },
  { id: "appointment_confirmation", title: "Appointment Confirmation", task: "Call the recipient and complete the appointment confirmation task.", success: ["confirmed", "completed", "yes"], failure: ["no answer", "declined", "unknown"] },
  { id: "reminder_confirmation", title: "Reminder Confirmation", task: "Call the recipient and complete the reminder confirmation task.", success: ["confirmed", "completed", "yes"], failure: ["no answer", "declined", "unknown"] },
  { id: "service_coordination", title: "Service Coordination", task: "Call the recipient and complete the service coordination task.", success: ["confirmed", "completed", "yes"], failure: ["no answer", "declined", "unknown"] },
  { id: "availability_check", title: "Availability Check", task: "Call the recipient and complete the availability check task.", success: ["confirmed", "completed", "yes"], failure: ["no answer", "declined", "unknown"] },
  { id: "callback_request", title: "Callback Request", task: "Call the recipient and complete the callback request task.", success: ["confirmed", "completed", "yes"], failure: ["no answer", "declined", "unknown"] },
  { id: "delivery_confirmation", title: "Delivery Confirmation", task: "Call the recipient and complete the delivery confirmation task.", success: ["confirmed", "completed", "yes"], failure: ["no answer", "declined", "unknown"] },
  { id: "lead_followup", title: "Lead Followup", task: "Call the recipient and complete the lead followup task.", success: ["confirmed", "completed", "yes"], failure: ["no answer", "declined", "unknown"] },
  { id: "renewal_confirmation", title: "Renewal Confirmation", task: "Call the recipient and complete the renewal confirmation task.", success: ["confirmed", "completed", "yes"], failure: ["no answer", "declined", "unknown"] },
  { id: "meeting_confirmation", title: "Meeting Confirmation", task: "Call the recipient and complete the meeting confirmation task.", success: ["confirmed", "completed", "yes"], failure: ["no answer", "declined", "unknown"] },
  { id: "reservation_check", title: "Reservation Check", task: "Call the recipient and complete the reservation check task.", success: ["confirmed", "completed", "yes"], failure: ["no answer", "declined", "unknown"] },
  { id: "hours_question", title: "Hours Question", task: "Call the recipient and complete the hours question task.", success: ["confirmed", "completed", "yes"], failure: ["no answer", "declined", "unknown"] },
  { id: "location_confirmation", title: "Location Confirmation", task: "Call the recipient and complete the location confirmation task.", success: ["confirmed", "completed", "yes"], failure: ["no answer", "declined", "unknown"] },
  { id: "document_collection", title: "Document Collection", task: "Call the recipient and complete the document collection task.", success: ["confirmed", "completed", "yes"], failure: ["no answer", "declined", "unknown"] },
  { id: "status_update", title: "Status Update", task: "Call the recipient and complete the status update task.", success: ["confirmed", "completed", "yes"], failure: ["no answer", "declined", "unknown"] },
  { id: "customer_feedback", title: "Customer Feedback", task: "Call the recipient and complete the customer feedback task.", success: ["confirmed", "completed", "yes"], failure: ["no answer", "declined", "unknown"] },
  { id: "vendor_followup", title: "Vendor Followup", task: "Call the recipient and complete the vendor followup task.", success: ["confirmed", "completed", "yes"], failure: ["no answer", "declined", "unknown"] },
  { id: "event_attendance", title: "Event Attendance", task: "Call the recipient and complete the event attendance task.", success: ["confirmed", "completed", "yes"], failure: ["no answer", "declined", "unknown"] },
  { id: "class_confirmation", title: "Class Confirmation", task: "Call the recipient and complete the class confirmation task.", success: ["confirmed", "completed", "yes"], failure: ["no answer", "declined", "unknown"] },
  { id: "support_callback", title: "Support Callback", task: "Call the recipient and complete the support callback task.", success: ["confirmed", "completed", "yes"], failure: ["no answer", "declined", "unknown"] },
  { id: "order_pickup", title: "Order Pickup", task: "Call the recipient and complete the order pickup task.", success: ["confirmed", "completed", "yes"], failure: ["no answer", "declined", "unknown"] },
  { id: "membership_confirmation", title: "Membership Confirmation", task: "Call the recipient and complete the membership confirmation task.", success: ["confirmed", "completed", "yes"], failure: ["no answer", "declined", "unknown"] },
  { id: "utility_outage_followup", title: "Utility Outage Followup", task: "Call the recipient and complete the utility outage followup task.", success: ["confirmed", "completed", "yes"], failure: ["no answer", "declined", "unknown"] },
  { id: "transport_check", title: "Transport Check", task: "Call the recipient and complete the transport check task.", success: ["confirmed", "completed", "yes"], failure: ["no answer", "declined", "unknown"] },
  { id: "school_admin_callback", title: "School Admin Callback", task: "Call the recipient and complete the school admin callback task.", success: ["confirmed", "completed", "yes"], failure: ["no answer", "declined", "unknown"] },
  { id: "clinic_admin_callback", title: "Clinic Admin Callback", task: "Call the recipient and complete the clinic admin callback task.", success: ["confirmed", "completed", "yes"], failure: ["no answer", "declined", "unknown"] },
  { id: "repair_schedule", title: "Repair Schedule", task: "Call the recipient and complete the repair schedule task.", success: ["confirmed", "completed", "yes"], failure: ["no answer", "declined", "unknown"] },
  { id: "insurance_callback", title: "Insurance Callback", task: "Call the recipient and complete the insurance callback task.", success: ["confirmed", "completed", "yes"], failure: ["no answer", "declined", "unknown"] },
  { id: "rental_confirmation", title: "Rental Confirmation", task: "Call the recipient and complete the rental confirmation task.", success: ["confirmed", "completed", "yes"], failure: ["no answer", "declined", "unknown"] },
  { id: "community_notice", title: "Community Notice", task: "Call the recipient and complete the community notice task.", success: ["confirmed", "completed", "yes"], failure: ["no answer", "declined", "unknown"] },
] as const;

export type CalleScenario = (typeof scenarios)[number];
