import type { AppLanguage } from "@/lib/language";
import { getHouseholdQueueCopy } from "@/lib/mock-households";

const english = {
  callAunty: "CALL AUNTY",
  greetingWoman: "Assalamu alaikum, Aisha",
  greetingChw: "Good morning, Salma",
  womanView: "Woman view",
  chwView: "CHW view",
  nextStep: "YOUR NEXT STEP",
  heroTitle: "A small check-in can keep care moving.",
  heroBody: "You are 24 weeks along. Aunty is here between visits.",
  startCheckIn: "Start today’s check-in",
  pauseHint: "About 2 minutes · You can pause",
  carePlan: "Your care plan",
  seeAll: "See all",
  voiceTitle: "Need a familiar voice?",
  voiceBody: "Call Aunty uses a neutral greeting for shared phones.",
  call: "Call",
  checkIn: "CHECK-IN",
  listeningTitle: "Aunty is listening",
  listeningBody: "Answer in the way that feels easiest. You can pause at any time.",
  yesHelp: "Yes — I need help",
  noToday: "No, not today",
  preferSpeak: "Prefer to speak? Call Aunty",
  holdToSpeak: "Hold to speak your answer",
  releaseToSend: "Release to send",
  voiceProcessing: "Listening…",
  voiceUnclear: "I could not catch that. Try again, or tap an answer below.",
  micPermissionBody: "Microphone access is needed for spoken answers. You can still tap Yes or No.",
  voiceOfflineBody: "Spoken answers need a connection. Tap Yes or No for now.",
  speakAnswerLabel: "Hold to speak yes or no",
  helpNow: "Please get help now",
  returnHome: "Return home",
  backHome: "Back to home",
  thankYou: "Thank you for checking in",
  leaveCheckIn: "Leave check-in",
  resume: "Resume",
  unfinishedTitle: "You have an unfinished check-in",
  unfinishedBody: "Your answers are saved on this device.",
  resumeLabel: "Resume unfinished check-in",
  careVisit: "ANC visit · 26 weeks",
  careVisitMeta: "Due in 12 days · Community clinic",
  fieldQueue: "FIELD QUEUE",
  actions: "actions",
  urgentCase: "One urgent case needs attention today.",
  savedSyncReady: "Saved on device · sync ready when connected",
  unlock: "Unlock",
  lock: "Lock",
  retry: "Retry",
  refreshQueue: "Refresh queue",
  prioritizedQueue: "Prioritized queue",
  queueClear: "Queue is clear",
  queueClearBody: "No follow-ups are waiting for your attention.",
  captureFollowUp: "Capture a follow-up",
  captureFollowUpBody: "Save offline and sync when connected",
  callHandoffTitle: "Call Aunty",
  callHandoffBody: "Your phone call handoff is ready. We will keep the greeting neutral until you confirm it is safe to continue.",
  callHandoffAction: "Continue to phone",
  callHandoffClose: "Not now",
  callHandoffFailed: "Phone dialer is unavailable on this device. Try again from a phone, or contact your health worker directly.",
  emergencyBody: "These symptoms can need an in-person assessment. Call your health worker or go to the nearest health facility now. Call Aunty cannot assess an emergency.",
  callHealthWorker: "Call my health worker",
  checkInQuestions: [
    "Do you have any heavy bleeding, severe pain, or trouble breathing right now?",
    "Since your last check-in, have you felt the baby move as usual?",
    "Do you have a care visit or follow-up that you need help arranging?",
  ],
  checkInProgress: (current: number, total: number) => `${current} of ${total}`,
  tabHome: "Home",
  tabCare: "Care plan",
  tabQueue: "Queue",
  tabSettings: "Settings",
  openQueue: "Open prioritized queue",
  openQueueBody: "Urgent cases appear first",
  guidanceClose: "Close",
  syncRefreshing: "Refreshing queue…",
  savedCheckInBody: "Your answers are saved on this device. Keep your next care visit on track, and call your health worker if anything changes.",
  privacyLockTitle: "Privacy lock is on",
  privacySyncBody: "Unlock sensitive records before refreshing or retrying sync.",
  syncUnavailableTitle: "Sync unavailable",
  syncUnavailableBody: "This follow-up remains saved on the device and can be retried when connected.",
  syncExhausted: "needs manual retry",
  syncDiagnosticTitle: "Sync check",
  syncOnline: "Internet is reachable",
  syncOffline: "Internet is not reachable",
  syncUnknown: "Internet status is unknown",
  syncDiagnosticQueued: "queued",
  syncDiagnosticRetrying: "retrying",
  syncDiagnosticSynced: "synced",
  syncDiagnosticExhausted: "need manual retry",
  reconciliationSynced: "follow-up(s) confirmed on the server",
  reconciliationPreserved: "local change(s) kept for retry",
  reconciliationFallback: "Server unavailable · local queue preserved",
  reconciliationHistory: "Last reconciliation",
  reconciliationHistoryServer: "server checked",
  reconciliationHistoryFallback: "local-only fallback",
  reconciliationHistoryTitle: "Recent reconciliation history",
  reconciliationHistoryOpen: "View recent history",
  reconciliationHistoryClose: "Close history",
  reconciliationHistoryEmpty: "No reconciliation history yet",
  reconciliationConflict: "Newer local changes kept · review before retrying",
  reconciliationKeepLocal: "Keep local",
  reconciliationAcceptServer: "Use server copy",
  reconciliationKeptLocal: "Local changes kept for retry",
  reconciliationAcceptedServer: "Server copy accepted and local queue updated",
  reconciliationAcceptTitle: "Use the server copy?",
  reconciliationAcceptBody: "This replaces the newer local version for the affected follow-up. Your local copy stays unchanged if you cancel.",
  reconciliationConfirm: "Use server copy",
  reconciliationCancel: "Cancel",
  reconciliationAcceptSummary: (count: number) => `${count} newer local change${count === 1 ? "" : "s"} will be replaced.`,
  reconciliationConfirmHint: "Apply the server copy and update the protected queue.",
  reconciliationDecisionKept: "kept local",
  reconciliationDecisionAccepted: "accepted server copy",
  reconciliationFilterAll: "All",
  reconciliationFilterKept: "Kept local",
  reconciliationFilterAccepted: "Accepted server",
  reconciliationFilterEmpty: "No entries match this filter",
  reconciliationLatestDecision: "Latest decision",
  reconciliationLatestDecisionEmpty: "No reconciliation decision recorded yet",
  reconciliationLatestCardTitle: "Latest decision",
  reconciliationLatestCardEmpty: "No sync decision yet",
  reconciliationLatestCardOpen: "View details",
  chwOpenCount: (count: number) => `${count} open`,
  chwCompletedCount: (count: number) => `${count} follow-up${count === 1 ? "" : "s"} completed on this device`,
  chwSyncItems: (count: number) => `${count} item${count === 1 ? "" : "s"}`,
  chwQueued: (count: number) => `${count} queued`,
  chwRetrying: (count: number) => `${count} retrying`,
  chwRetryQueued: "Retry queued sync",
  chwNewFollowUp: "Capture a new follow-up",
  chwNewFollowUpTitle: "New follow-up",
  chwNewFollowUpBody: "Follow-up capture is ready for a woman record.",
  todayFocus: "Start here",
  syncTools: "Sync & records",
  filterAll: "All",
  filterUrgent: "Urgent",
  filterAttention: "Needs attention",
  filterRoutine: "Routine",
  filterEmpty: "No cases match this filter",
  headerCall: "Call now",
  searchPlaceholder: "Name or village",
  fieldActivity: "Field activity",
  fieldActivityBody: "Today’s mock route and CALL-E log",
  chwQueue: [
    { name: "Rina Begum", meta: "32 weeks · check-in missed", urgency: "Urgent", nextAction: "Call today" },
    { name: "Shahana Akter", meta: "24 weeks · referral pending", urgency: "Needs attention", nextAction: "Confirm referral" },
    { name: "Mousumi Khatun", meta: "18 weeks · due today", urgency: "Routine", nextAction: "Visit due today" },
  ],
  unexpectedErrorTitle: "Something went wrong",
  unexpectedErrorBody: "Your local records are still protected. Try again, or continue when the connection is stable.",
  syncFallbackNotice: "Could not refresh from the server · local queue preserved",
  privacyActionError: "The privacy lock could not be changed. Your protected records remain safe.",
};

const bangla = {
  callAunty: "কল আন্টি",
  greetingWoman: "আসসালামু আলাইকুম, আয়েশা",
  greetingChw: "সুপ্রভাত, সালমা",
  womanView: "নারীর দৃশ্য",
  chwView: "সিএইচডব্লিউ দৃশ্য",
  nextStep: "আপনার পরবর্তী ধাপ",
  heroTitle: "ছোট একটি চেক-ইন যত্নকে এগিয়ে রাখতে পারে।",
  heroBody: "আপনার গর্ভাবস্থার ২৪ সপ্তাহ চলছে। দেখা করার মাঝেও আন্টি পাশে আছেন।",
  startCheckIn: "আজকের চেক-ইন শুরু করুন",
  pauseHint: "প্রায় ২ মিনিট · চাইলে বিরতি নিতে পারেন",
  carePlan: "আপনার যত্নের পরিকল্পনা",
  seeAll: "সব দেখুন",
  voiceTitle: "পরিচিত কণ্ঠ দরকার?",
  voiceBody: "শেয়ার করা ফোনে কল আন্টি নিরপেক্ষ শুভেচ্ছা ব্যবহার করে।",
  call: "কল",
  checkIn: "চেক-ইন",
  listeningTitle: "আন্টি শুনছেন",
  listeningBody: "যেভাবে স্বস্তি লাগে সেভাবে উত্তর দিন। চাইলে যেকোনো সময় বিরতি নিতে পারেন।",
  yesHelp: "হ্যাঁ — আমার সাহায্য দরকার",
  noToday: "না, আজ নয়",
  preferSpeak: "কথা বলতে চান? কল আন্টি",
  holdToSpeak: "উত্তর বলতে চেপে ধরুন",
  releaseToSend: "পাঠাতে ছেড়ে দিন",
  voiceProcessing: "শুনছি…",
  voiceUnclear: "বুঝতে পারিনি। আবার চেষ্টা করুন, বা নিচের উত্তরে ট্যাপ করুন।",
  micPermissionBody: "কণ্ঠে উত্তর দিতে মাইক্রোফোন দরকার। চাইলে হ্যাঁ/না-তে ট্যাপ করতে পারেন।",
  voiceOfflineBody: "কণ্ঠে উত্তর দিতে সংযোগ দরকার। এখন হ্যাঁ/না ট্যাপ করুন।",
  speakAnswerLabel: "হ্যাঁ বা না বলতে চেপে ধরুন",
  helpNow: "এখনই সাহায্য নিন",
  returnHome: "হোমে ফিরুন",
  backHome: "হোমে ফিরুন",
  thankYou: "চেক-ইন করার জন্য ধন্যবাদ",
  leaveCheckIn: "চেক-ইন ছেড়ে দিন",
  resume: "চালিয়ে যান",
  unfinishedTitle: "আপনার একটি অসম্পূর্ণ চেক-ইন আছে",
  unfinishedBody: "আপনার উত্তরগুলো এই ডিভাইসে সংরক্ষিত আছে।",
  resumeLabel: "অসম্পূর্ণ চেক-ইন চালিয়ে যান",
  careVisit: "এএনসি ভিজিট · ২৬ সপ্তাহ",
  careVisitMeta: "১২ দিনের মধ্যে · কমিউনিটি ক্লিনিক",
  fieldQueue: "ফিল্ড কিউ",
  actions: "টি কাজ",
  urgentCase: "আজ একটি জরুরি কেসে মনোযোগ দরকার।",
  savedSyncReady: "ডিভাইসে সংরক্ষিত · সংযোগ হলে সিঙ্ক হবে",
  unlock: "আনলক",
  lock: "লক",
  retry: "আবার চেষ্টা",
  refreshQueue: "কিউ রিফ্রেশ করুন",
  prioritizedQueue: "অগ্রাধিকার কিউ",
  queueClear: "কিউ খালি",
  queueClearBody: "আপনার মনোযোগের অপেক্ষায় কোনো ফলো-আপ নেই।",
  captureFollowUp: "ফলো-আপ নথিভুক্ত করুন",
  captureFollowUpBody: "অফলাইনে সংরক্ষণ করুন, সংযোগ হলে সিঙ্ক হবে",
  callHandoffTitle: "কল আন্টি",
  callHandoffBody: "আপনার ফোন কলের প্রস্তুতি সম্পন্ন। নিরাপদ কিনা নিশ্চিত না হওয়া পর্যন্ত শুভেচ্ছাটি নিরপেক্ষ রাখা হবে।",
  callHandoffAction: "ফোনে চালিয়ে যান",
  callHandoffClose: "এখন নয়",
  callHandoffFailed: "এই ডিভাইসে ফোন ডায়ালার নেই। ফোন থেকে আবার চেষ্টা করুন, অথবা সরাসরি স্বাস্থ্যকর্মীকে যোগাযোগ করুন।",
  emergencyBody: "এই লক্ষণগুলো সরাসরি মূল্যায়নের প্রয়োজন হতে পারে। এখনই আপনার স্বাস্থ্যকর্মীকে কল করুন বা নিকটস্থ স্বাস্থ্যকেন্দ্রে যান। কল আন্টি জরুরি অবস্থা মূল্যায়ন করতে পারে না।",
  callHealthWorker: "আমার স্বাস্থ্যকর্মীকে কল করুন",
  checkInQuestions: [
    "এখন কি আপনার অতিরিক্ত রক্তপাত, তীব্র ব্যথা বা শ্বাসকষ্ট আছে?",
    "শেষ চেক-ইনের পর থেকে কি শিশু আগের মতো নড়াচড়া করছে?",
    "কোনো যত্নের ভিজিট বা ফলো-আপ সাজাতে কি আপনার সাহায্য দরকার?",
  ],
  checkInProgress: (current: number, total: number) => `${current} এর ${total}`,
  tabHome: "হোম",
  tabCare: "যত্নের পরিকল্পনা",
  tabQueue: "কিউ",
  tabSettings: "সেটিংস",
  openQueue: "অগ্রাধিকার কিউ খুলুন",
  openQueueBody: "জরুরি কেস আগে দেখা যায়",
  guidanceClose: "বন্ধ করুন",
  syncRefreshing: "কিউ রিফ্রেশ হচ্ছে…",
  savedCheckInBody: "আপনার উত্তরগুলো এই ডিভাইসে সংরক্ষিত আছে। পরবর্তী যত্নের ভিজিট ঠিক রাখতে এবং পরিবর্তন হলে স্বাস্থ্যকর্মীকে কল করুন।",
  privacyLockTitle: "প্রাইভেসি লক চালু আছে",
  privacySyncBody: "রিফ্রেশ বা সিঙ্ক আবার চেষ্টা করার আগে সংবেদনশীল রেকর্ড আনলক করুন।",
  syncUnavailableTitle: "সিঙ্ক এখন সম্ভব নয়",
  syncUnavailableBody: "এই ফলো-আপটি ডিভাইসে সংরক্ষিত আছে এবং সংযোগ হলে আবার চেষ্টা করা যাবে।",
  syncExhausted: "ম্যানুয়াল চেষ্টা দরকার",
  syncDiagnosticTitle: "সিঙ্ক পরীক্ষা",
  syncOnline: "ইন্টারনেট সংযোগ পাওয়া গেছে",
  syncOffline: "ইন্টারনেট সংযোগ পাওয়া যায়নি",
  syncUnknown: "ইন্টারনেটের অবস্থা জানা যায়নি",
  syncDiagnosticQueued: "কিউতে",
  syncDiagnosticRetrying: "আবার চেষ্টা হচ্ছে",
  syncDiagnosticSynced: "সিঙ্ক হয়েছে",
  syncDiagnosticExhausted: "ম্যানুয়াল চেষ্টা দরকার",
  reconciliationSynced: "টি ফলো-আপ সার্ভারে নিশ্চিত হয়েছে",
  reconciliationPreserved: "টি লোকাল পরিবর্তন আবার চেষ্টা করার জন্য রাখা হয়েছে",
  reconciliationFallback: "সার্ভার পাওয়া যায়নি · লোকাল কিউ রাখা হয়েছে",
  reconciliationHistory: "সর্বশেষ রিকনসাইল",
  reconciliationHistoryServer: "সার্ভার দেখা হয়েছে",
  reconciliationHistoryFallback: "শুধু লোকাল বিকল্প",
  reconciliationHistoryTitle: "সাম্প্রতিক রিকনসাইল ইতিহাস",
  reconciliationHistoryOpen: "সাম্প্রতিক ইতিহাস দেখুন",
  reconciliationHistoryClose: "ইতিহাস বন্ধ করুন",
  reconciliationHistoryEmpty: "এখনও কোনো রিকনসাইল ইতিহাস নেই",
  reconciliationConflict: "নতুন লোকাল পরিবর্তন রাখা হয়েছে · আবার চেষ্টা করার আগে দেখুন",
  reconciliationKeepLocal: "লোকাল রাখুন",
  reconciliationAcceptServer: "সার্ভারের কপি নিন",
  reconciliationKeptLocal: "লোকাল পরিবর্তন আবার চেষ্টা করার জন্য রাখা হয়েছে",
  reconciliationAcceptedServer: "সার্ভারের কপি গ্রহণ করে লোকাল কিউ আপডেট হয়েছে",
  reconciliationAcceptTitle: "সার্ভারের কপি নেবেন?",
  reconciliationAcceptBody: "এটি সংশ্লিষ্ট ফলো-আপের নতুন লোকাল সংস্করণ বদলে দেবে। বাতিল করলে লোকাল কপি অপরিবর্তিত থাকবে।",
  reconciliationConfirm: "সার্ভারের কপি নিন",
  reconciliationCancel: "বাতিল",
  reconciliationAcceptSummary: (count: number) => `${count}টি নতুন লোকাল পরিবর্তন বদলে যাবে।`,
  reconciliationConfirmHint: "সার্ভারের কপি প্রয়োগ করে সুরক্ষিত কিউ আপডেট করুন।",
  reconciliationDecisionKept: "লোকাল রাখা হয়েছে",
  reconciliationDecisionAccepted: "সার্ভারের কপি নেওয়া হয়েছে",
  reconciliationFilterAll: "সব",
  reconciliationFilterKept: "লোকাল রাখা হয়েছে",
  reconciliationFilterAccepted: "সার্ভার নেওয়া হয়েছে",
  reconciliationFilterEmpty: "এই ফিল্টারে কোনো এন্ট্রি নেই",
  reconciliationLatestDecision: "সর্বশেষ সিদ্ধান্ত",
  reconciliationLatestDecisionEmpty: "এখনও কোনো সমন্বয় সিদ্ধান্ত রেকর্ড হয়নি",
  reconciliationLatestCardTitle: "সর্বশেষ সিদ্ধান্ত",
  reconciliationLatestCardEmpty: "এখনও কোনো সিঙ্ক সিদ্ধান্ত নেই",
  reconciliationLatestCardOpen: "বিস্তারিত দেখুন",
  chwOpenCount: (count: number) => `${count}টি খোলা`,
  chwCompletedCount: (count: number) => `এই ডিভাইসে ${count}টি ফলো-আপ সম্পন্ন হয়েছে`,
  chwSyncItems: (count: number) => `${count}টি আইটেম`,
  chwQueued: (count: number) => `${count}টি কিউতে`,
  chwRetrying: (count: number) => `${count}টি আবার চেষ্টা হচ্ছে`,
  chwRetryQueued: "কিউয়ের সিঙ্ক আবার চেষ্টা করুন",
  chwNewFollowUp: "নতুন ফলো-আপ নথিভুক্ত করুন",
  chwNewFollowUpTitle: "নতুন ফলো-আপ",
  chwNewFollowUpBody: "একজন নারীর রেকর্ডের জন্য ফলো-আপ নথিভুক্ত করা প্রস্তুত।",
  todayFocus: "এখান থেকে শুরু করুন",
  syncTools: "সিঙ্ক ও রেকর্ড",
  filterAll: "সব",
  filterUrgent: "জরুরি",
  filterAttention: "মনোযোগ দরকার",
  filterRoutine: "নিয়মিত",
  filterEmpty: "এই ফিল্টারে কোনো কেস নেই",
  headerCall: "এখনই কল",
  searchPlaceholder: "নাম বা গ্রাম",
  fieldActivity: "ফিল্ড অ্যাকটিভিটি",
  fieldActivityBody: "আজকের মক রুট ও CALL-E লগ",
  chwQueue: [
    { name: "রিনা বেগম", meta: "৩২ সপ্তাহ · চেক-ইন বাকি", urgency: "জরুরি", nextAction: "আজ কল করুন" },
    { name: "শাহানা আক্তার", meta: "২৪ সপ্তাহ · রেফারেল বাকি", urgency: "মনোযোগ দরকার", nextAction: "রেফারেল নিশ্চিত করুন" },
    { name: "মৌসুমি খাতুন", meta: "১৮ সপ্তাহ · আজকের কাজ", urgency: "নিয়মিত", nextAction: "আজকের ভিজিট" },
  ],
  unexpectedErrorTitle: "কিছু সমস্যা হয়েছে",
  unexpectedErrorBody: "আপনার লোকাল রেকর্ড সুরক্ষিত আছে। আবার চেষ্টা করুন, অথবা সংযোগ স্থির হলে চালিয়ে যান।",
  syncFallbackNotice: "সার্ভার থেকে রিফ্রেশ করা যায়নি · লোকাল কিউ রাখা হয়েছে",
  privacyActionError: "প্রাইভেসি লক পরিবর্তন করা যায়নি। আপনার সুরক্ষিত রেকর্ড নিরাপদ আছে।",
};

const hindi = {
  ...english,
  callAunty: "कॉल आंटी",
  greetingWoman: "अस्सलामु अलैकुम, आयशा",
  greetingChw: "सुप्रभात, सलमा",
  womanView: "महिला दृश्य",
  chwView: "सीएचडब्ल्यू दृश्य",
  nextStep: "आपका अगला कदम",
  heroTitle: "एक छोटा चेक-इन देखभाल को आगे बढ़ा सकता है।",
  startCheckIn: "आज का चेक-इन शुरू करें",
  pauseHint: "लगभग २ मिनट · आप रोक सकती हैं",
  carePlan: "आपकी देखभाल योजना",
  seeAll: "सब देखें",
  voiceTitle: "क्या आपको परिचित आवाज़ चाहिए?",
  call: "कॉल",
  checkIn: "चेक-इन",
  helpNow: "अभी मदद लें",
  returnHome: "होम लौटें",
  backHome: "होम पर वापस जाएँ",
  savedSyncReady: "डिवाइस पर सहेजा गया · कनेक्शन होने पर सिंक होगा",
  unlock: "अनलॉक",
  lock: "लॉक",
  retry: "फिर कोशिश करें",
  refreshQueue: "क्यू रीफ्रेश करें",
  prioritizedQueue: "प्राथमिकता क्यू",
  queueClear: "क्यू खाली है",
  captureFollowUp: "फॉलो-अप दर्ज करें",
  callHandoffTitle: "कॉल आंटी",
  emergencyBody: "इन लक्षणों के लिए व्यक्तिगत जाँच की ज़रूरत हो सकती है। अभी अपने स्वास्थ्यकर्मी को कॉल करें या नज़दीकी स्वास्थ्य केंद्र जाएँ। कॉल आंटी आपात स्थिति का आकलन नहीं कर सकती।",
  privacyLockTitle: "प्राइवेसी लॉक चालू है",
  privacySyncBody: "रीफ्रेश या सिंक दोबारा करने से पहले संवेदनशील रिकॉर्ड अनलॉक करें।",
  syncUnavailableTitle: "सिंक उपलब्ध नहीं है",
  syncUnavailableBody: "यह फॉलो-अप डिवाइस पर सुरक्षित है और कनेक्शन होने पर फिर कोशिश की जा सकती है।",
  reconciliationHistoryTitle: "हाल का रीकन्सिलिएशन इतिहास",
  reconciliationHistoryOpen: "हाल का इतिहास देखें",
  reconciliationHistoryClose: "इतिहास बंद करें",
  unexpectedErrorTitle: "कुछ गलत हो गया",
  unexpectedErrorBody: "आपके स्थानीय रिकॉर्ड सुरक्षित हैं। फिर कोशिश करें या कनेक्शन स्थिर होने पर जारी रखें।",
  searchPlaceholder: "नाम या गाँव",
  fieldActivity: "फ़ील्ड गतिविधि",
  fieldActivityBody: "आज का मॉक रूट और CALL-E लॉग",
};

const urdu = {
  ...english,
  callAunty: "کال آنٹی",
  greetingWoman: "السلام علیکم، عائشہ",
  greetingChw: "صبح بخیر، سلمیٰ",
  womanView: "خاتون کا منظر",
  chwView: "سی ایچ ڈبلیو منظر",
  nextStep: "آپ کا اگلا قدم",
  heroTitle: "ایک مختصر چیک اِن دیکھ بھال کو جاری رکھ سکتا ہے۔",
  startCheckIn: "آج کا چیک اِن شروع کریں",
  pauseHint: "تقریباً ۲ منٹ · آپ روک سکتی ہیں",
  carePlan: "آپ کی دیکھ بھال کا منصوبہ",
  seeAll: "سب دیکھیں",
  voiceTitle: "کیا آپ کو جانی پہچانی آواز چاہیے؟",
  call: "کال",
  checkIn: "چیک اِن",
  helpNow: "ابھی مدد لیں",
  returnHome: "گھر واپس جائیں",
  backHome: "گھر واپس جائیں",
  savedSyncReady: "ڈیوائس پر محفوظ · کنکشن ہونے پر ہم وقت ہوگا",
  unlock: "ان لاک",
  lock: "لاک",
  retry: "دوبارہ کوشش",
  refreshQueue: "قطار تازہ کریں",
  prioritizedQueue: "ترجیحی قطار",
  queueClear: "قطار خالی ہے",
  captureFollowUp: "فالو اَپ درج کریں",
  callHandoffTitle: "کال آنٹی",
  emergencyBody: "ان علامات کے لیے ذاتی معائنہ ضروری ہو سکتا ہے۔ ابھی اپنے صحت کارکن کو کال کریں یا قریبی مرکزِ صحت جائیں۔ کال آنٹی ہنگامی حالت کا جائزہ نہیں لے سکتی۔",
  privacyLockTitle: "پرائیویسی لاک فعال ہے",
  privacySyncBody: "تازہ کرنے یا ہم وقت کرنے سے پہلے حساس ریکارڈ ان لاک کریں۔",
  syncUnavailableTitle: "ہم وقت سازی دستیاب نہیں",
  syncUnavailableBody: "یہ فالو اَپ ڈیوائس پر محفوظ ہے اور کنکشن ہونے پر دوبارہ کوشش کی جا سکتی ہے۔",
  reconciliationHistoryTitle: "حالیہ ریکنسیلی ایشن تاریخ",
  reconciliationHistoryOpen: "حالیہ تاریخ دیکھیں",
  reconciliationHistoryClose: "تاریخ بند کریں",
  unexpectedErrorTitle: "کچھ غلط ہو گیا",
  unexpectedErrorBody: "آپ کے مقامی ریکارڈ محفوظ ہیں۔ دوبارہ کوشش کریں یا کنکشن مستحکم ہونے پر جاری رکھیں۔",
  searchPlaceholder: "نام یا گاؤں",
  fieldActivity: "فیلڈ سرگرمی",
  fieldActivityBody: "آج کا ماک روٹ اور CALL-E لاگ",
};

const appCopyByLanguage: Partial<Record<AppLanguage, typeof english>> = { bn: bangla, en: english, hi: hindi, ur: urdu };

export function getAppCopy(language: AppLanguage) {
  const base = appCopyByLanguage[language] ?? english;
  return {
    ...base,
    chwQueue: getHouseholdQueueCopy(language),
  };
}

const careEnglish = {
  eyebrow: "YOUR CARE PLAN",
  title: "Small steps, remembered.",
  subtitle: "Aunty keeps the next action close, so you do not have to carry it all in your head.",
  journey: "PREGNANCY JOURNEY",
  stageTitle: "24 weeks",
  stageMeta: "Second trimester · routine follow-up",
  referralMeta: "Salma · Community clinic",
  upcoming: "Upcoming",
  healthWorker: "Your health worker",
  call: "Call",
  sharedPlan: "This care item is part of your shared care plan.",
};

const careBangla = {
  eyebrow: "আপনার যত্নের পরিকল্পনা",
  title: "ছোট ধাপগুলো মনে থাকবে।",
  subtitle: "পরবর্তী কাজটি আন্টি মনে রাখবেন, তাই সবকিছু আপনাকে একা মনে রাখতে হবে না।",
  journey: "গর্ভাবস্থার যাত্রা",
  stageTitle: "২৪ সপ্তাহ",
  stageMeta: "দ্বিতীয় ত্রৈমাসিক · নিয়মিত ফলো-আপ",
  referralMeta: "সালমা · কমিউনিটি ক্লিনিক",
  upcoming: "আসন্ন",
  healthWorker: "আপনার স্বাস্থ্যকর্মী",
  call: "কল",
  sharedPlan: "এই যত্নের কাজটি আপনার যৌথ যত্ন পরিকল্পনার অংশ।",
};

const careHindi = {
  ...careEnglish,
  eyebrow: "आपकी देखभाल योजना",
  title: "छोटे कदम, याद रहेंगे।",
  subtitle: "आंटी अगला काम पास रखती हैं, ताकि आपको सब कुछ अकेले याद न रखना पड़े।",
  journey: "गर्भावस्था की यात्रा",
  stageTitle: "२४ सप्ताह",
  stageMeta: "दूसरी तिमाही · नियमित फॉलो-अप",
  referralMeta: "सलमा · सामुदायिक क्लिनिक",
  upcoming: "आने वाला",
  healthWorker: "आपका स्वास्थ्यकर्मी",
  call: "कॉल",
  sharedPlan: "यह देखभाल का काम आपकी साझा देखभाल योजना का हिस्सा है।",
};

const careUrdu = {
  ...careEnglish,
  eyebrow: "آپ کی دیکھ بھال کا منصوبہ",
  title: "چھوٹے قدم یاد رہیں گے۔",
  subtitle: "آنٹی اگلا کام سامنے رکھتی ہیں تاکہ آپ کو سب کچھ اکیلے یاد نہ رکھنا پڑے۔",
  journey: "حمل کا سفر",
  stageTitle: "۲۴ ہفتے",
  stageMeta: "دوسری سہ ماہی · معمول کا فالو اَپ",
  referralMeta: "سلمیٰ · کمیونٹی کلینک",
  upcoming: "آنے والا",
  healthWorker: "آپ کا صحت کارکن",
  call: "کال",
  sharedPlan: "یہ دیکھ بھال کا کام آپ کے مشترکہ منصوبے کا حصہ ہے۔",
};

const careCopyByLanguage: Partial<Record<AppLanguage, typeof careEnglish>> = { bn: careBangla, en: careEnglish, hi: careHindi, ur: careUrdu };

export function getCareCopy(language: AppLanguage) {
  return careCopyByLanguage[language] ?? careEnglish;
}

const chwDetailEnglish = {
  back: "Queue",
  eyebrow: "WOMAN RECORD",
  weeksMeta: "24 weeks · prefers Bangla · safe window 6–8 PM",
  referralTitle: "Referral pending",
  referralBody: "Confirm whether the clinic contact happened and record the next step.",
  nextAction: "Next action",
  captureTitle: "Capture follow-up",
  captureBody: "Save the contact outcome and next action offline",
  captureLabel: "Capture follow-up for this woman",
  callTitle: "Start phone follow-up",
  callBody: "Prepare a CALL-E dry-run, then confirm side effects",
  callLabel: "Start CALL-E phone follow-up for this woman",
  callAlertTitle: "Phone follow-up",
  callAlertBody:
    "This prepares a server-side CALL-E workflow. Default mode is dry-run: no live call is placed. Call language is English (US). Bangla UI copy is separate from spoken call language.",
  confirmTitle: "Confirm phone follow-up",
  confirmPrimary: "Confirm",
  preparePrimary: "Prepare dry-run",
  dialerFallback: "Open dialer instead",
  dialerFallbackDetail: "Use the phone dialer if CALL-E is unavailable",
  commandCenter: "Open call command center",
  calleAgent: "Open CALL-E phone agent",
  consentLabel: "I confirm call consent is recorded for this follow-up",
  dryRunBadge: "DRY-RUN",
  statusLabel: "Call status",
  resultSaved: "Follow-up updated from phone workflow",
  prepareError: "Could not prepare the phone workflow. Check sign-in and try again.",
  confirmError: "Could not confirm the phone workflow.",
  policyDenied: "Policy blocked this call. Keep human escalation primary.",
  summary: "Structured summary",
  lastCheckIn: "Last check-in",
  lastCheckInValue: "Yesterday · routine",
  careContact: "Care contact",
  careContactValue: "ANC visit due in 12 days",
  openTask: "Open task",
  openTaskValue: "Referral acknowledgement",
};

const chwDetailBangla = {
  ...chwDetailEnglish,
  back: "কিউ",
  eyebrow: "নারীর রেকর্ড",
  weeksMeta: "২৪ সপ্তাহ · বাংলা পছন্দ · নিরাপদ সময় সন্ধ্যা ৬–৮টা",
  referralTitle: "রেফারেল অপেক্ষমাণ",
  referralBody: "ক্লিনিকের সঙ্গে যোগাযোগ হয়েছে কি না নিশ্চিত করুন এবং পরবর্তী কাজ লিখুন।",
  nextAction: "পরবর্তী কাজ",
  captureTitle: "ফলো-আপ নথিভুক্ত করুন",
  captureBody: "যোগাযোগের ফলাফল ও পরবর্তী কাজ অফলাইনে সংরক্ষণ করুন",
  captureLabel: "এই নারীর ফলো-আপ নথিভুক্ত করুন",
  callTitle: "ফোন ফলো-আপ শুরু করুন",
  callBody: "CALL-E ড্রাই-রান প্রস্তুত করুন, তারপর পার্শ্বপ্রতিক্রিয়া নিশ্চিত করুন",
  callLabel: "এই নারীর জন্য CALL-E ফোন ফলো-আপ শুরু করুন",
  callAlertTitle: "ফোন ফলো-আপ",
  callAlertBody:
    "এটি সার্ভার-সাইড CALL-E ওয়ার্কফ্লো প্রস্তুত করে। ডিফল্ট মোড ড্রাই-রান: কোনো লাইভ কল যাবে না। কলের ভাষা ইংরেজি (US)। বাংলা UI আলাদা।",
  confirmTitle: "ফোন ফলো-আপ নিশ্চিত করুন",
  confirmPrimary: "নিশ্চিত করুন",
  preparePrimary: "ড্রাই-রান প্রস্তুত",
  dialerFallback: "ডায়ালার খুলুন",
  dialerFallbackDetail: "CALL-E না থাকলে ফোন ডায়ালার ব্যবহার করুন",
  commandCenter: "কল কমান্ড সেন্টার খুলুন",
  calleAgent: "CALL-E ফোন এজেন্ট খুলুন",
  consentLabel: "এই ফলো-আপের জন্য কল সম্মতি নথিভুক্ত আছে",
  dryRunBadge: "ড্রাই-রান",
  statusLabel: "কলের অবস্থা",
  resultSaved: "ফোন ওয়ার্কফ্লো থেকে ফলো-আপ আপডেট হয়েছে",
  prepareError: "ফোন ওয়ার্কফ্লো প্রস্তুত করা যায়নি। সাইন-ইন পরীক্ষা করুন।",
  confirmError: "ফোন ওয়ার্কফ্লো নিশ্চিত করা যায়নি।",
  policyDenied: "নীতি এই কল আটকেছে। মানুষের এসকেলেশন প্রাথমিক রাখুন।",
  summary: "সংগঠিত সারাংশ",
  lastCheckIn: "সর্বশেষ চেক-ইন",
  lastCheckInValue: "গতকাল · নিয়মিত",
  careContact: "যত্নের যোগাযোগ",
  careContactValue: "১২ দিনের মধ্যে এএনসি ভিজিট",
  openTask: "খোলা কাজ",
  openTaskValue: "রেফারেল নিশ্চিতকরণ",
};

const chwDetailHindi = {
  ...chwDetailEnglish,
  back: "क्यू",
  eyebrow: "महिला रिकॉर्ड",
  weeksMeta: "२४ सप्ताह · हिन्दी पसंद · सुरक्षित समय शाम ६–८ बजे",
  referralTitle: "रेफरल लंबित",
  referralBody: "पुष्टि करें कि क्लिनिक से संपर्क हुआ या नहीं और अगला कदम दर्ज करें।",
  nextAction: "अगला कदम",
  captureTitle: "फॉलो-अप दर्ज करें",
  captureBody: "संपर्क का परिणाम और अगला कदम ऑफलाइन सहेजें",
  captureLabel: "इस महिला का फॉलो-अप दर्ज करें",
  callTitle: "फोन फॉलो-अप शुरू करें",
  callBody: "CALL-E ड्राई-रन तैयार करें, फिर साइड इफ़ेक्ट की पुष्टि करें",
  callLabel: "इस महिला के लिए CALL-E फोन फॉलो-अप शुरू करें",
  callAlertTitle: "फोन फॉलो-अप",
  callAlertBody:
    "यह सर्वर-साइड CALL-E वर्कफ़्लो तैयार करता है। डिफ़ॉल्ट मोड ड्राई-रन है: कोई लाइव कॉल नहीं। कॉल भाषा अंग्रेज़ी (US) है।",
  confirmTitle: "फोन फॉलो-अप की पुष्टि करें",
  confirmPrimary: "पुष्टि करें",
  preparePrimary: "ड्राई-रन तैयार करें",
  dialerFallback: "डायलर खोलें",
  dialerFallbackDetail: "CALL-E उपलब्ध न हो तो फ़ोन डायलर इस्तेमाल करें",
  commandCenter: "कॉल कमांड सेंटर खोलें",
  calleAgent: "CALL-E फ़ोन एजेंट खोलें",
  consentLabel: "इस फॉलो-अप के लिए कॉल सहमति दर्ज है",
  dryRunBadge: "ड्राई-रन",
  statusLabel: "कॉल स्थिति",
  resultSaved: "फोन वर्कफ़्लो से फॉलो-अप अपडेट हुआ",
  prepareError: "फोन वर्कफ़्लो तैयार नहीं हो सका। साइन-इन जाँचें।",
  confirmError: "फोन वर्कफ़्लो की पुष्टि नहीं हो सकी।",
  policyDenied: "नीति ने यह कॉल रोकी। मानवीय एस्केलेशन प्राथमिक रखें।",
  summary: "संरचित सारांश",
  lastCheckIn: "पिछला चेक-इन",
  lastCheckInValue: "कल · नियमित",
  careContact: "देखभाल संपर्क",
  careContactValue: "१२ दिनों में एएनसी विज़िट",
  openTask: "खुला काम",
  openTaskValue: "रेफरल की पुष्टि",
};

const chwDetailUrdu = {
  ...chwDetailEnglish,
  back: "قطار",
  eyebrow: "خاتون کا ریکارڈ",
  weeksMeta: "۲۴ ہفتے · اردو پسند · محفوظ وقت شام ۶–۸ بجے",
  referralTitle: "ریفرل زیر التوا",
  referralBody: "تصدیق کریں کہ مرکز سے رابطہ ہوا یا نہیں اور اگلا قدم درج کریں۔",
  nextAction: "اگلا قدم",
  captureTitle: "فالو اَپ درج کریں",
  captureBody: "رابطے کا نتیجہ اور اگلا قدم آف لائن محفوظ کریں",
  captureLabel: "اس خاتون کا فالو اَپ درج کریں",
  callTitle: "فون فالو اَپ شروع کریں",
  callBody: "CALL-E ڈرائی رن تیار کریں، پھر ضمنی اثرات کی تصدیق کریں",
  callLabel: "اس خاتون کے لیے CALL-E فون فالو اَپ شروع کریں",
  callAlertTitle: "فون فالو اَپ",
  callAlertBody:
    "یہ سرور سائیڈ CALL-E ورک فلو تیار کرتا ہے۔ ڈیفالٹ موڈ ڈرائی رن ہے: کوئی لائیو کال نہیں۔ کال کی زبان انگریزی (US) ہے۔",
  confirmTitle: "فون فالو اَپ کی تصدیق کریں",
  confirmPrimary: "تصدیق کریں",
  preparePrimary: "ڈرائی رن تیار کریں",
  dialerFallback: "ڈائلر کھولیں",
  dialerFallbackDetail: "CALL-E دستیاب نہ ہو تو فون ڈائلر استعمال کریں",
  commandCenter: "کال کمانڈ سینٹر کھولیں",
  calleAgent: "CALL-E فون ایجنٹ کھولیں",
  consentLabel: "اس فالو اَپ کے لیے کال کی رضامندی درج ہے",
  dryRunBadge: "ڈرائی رن",
  statusLabel: "کال کی حالت",
  resultSaved: "فون ورک فلو سے فالو اَپ اپ ڈیٹ ہوا",
  prepareError: "فون ورک فلو تیار نہیں ہو سکا۔ سائن اِن چیک کریں۔",
  confirmError: "فون ورک فلو کی تصدیق نہیں ہو سکی۔",
  policyDenied: "پالیسی نے یہ کال روک دی۔ انسانی ایکسیلریشن بنیادی رکھیں۔",
  summary: "منظم خلاصہ",
  lastCheckIn: "آخری چیک اِن",
  lastCheckInValue: "کل · معمول کے مطابق",
  careContact: "دیکھ بھال کا رابطہ",
  careContactValue: "۱۲ دن میں اے این سی وزٹ",
  openTask: "کھلا کام",
  openTaskValue: "ریفرل کی تصدیق",
};

const chwDetailCopyByLanguage: Partial<Record<AppLanguage, typeof chwDetailEnglish>> = { bn: chwDetailBangla, en: chwDetailEnglish, hi: chwDetailHindi, ur: chwDetailUrdu };

export function getChwDetailCopy(language: AppLanguage) {
  return chwDetailCopyByLanguage[language] ?? chwDetailEnglish;
}

const followUpEnglish = {
  back: "Cancel",
  eyebrow: "CHW FOLLOW-UP",
  title: (id: string) => `What happened with ${id}?`,
  subtitle: "Keep the record short, structured, and focused on the next action.",
  restored: "Draft restored from this device.",
  contactMethod: "Contact method",
  outcome: "Outcome",
  note: "Short note",
  noteLabel: "Follow-up note",
  notePlaceholder: "Example: spoke with mother; clinic visit confirmed",
  noteRequired: "Add a short note about the contact.",
  noteHelper: "This note stays on the device until sync is available.",
  nextAction: "Next action",
  save: "Save follow-up",
  saveLabel: "Save follow-up",
  savedTitle: "Follow-up saved",
  savedBody: "The completed contact is stored on this device and ready for sync.",
  done: "Done",
  saveErrorTitle: "Could not save follow-up",
  saveErrorBody: "The record stayed unchanged. Check local storage and try again.",
  pickPersonTitle: "Who did you contact?",
  pickPersonBody: "Choose a woman from today’s queue, then record what happened.",
  contactOptions: { visit: "Visit", phone: "Phone", sms: "SMS" },
  outcomeOptions: { reached: "Reached", no_answer: "No answer", needs_clinician: "Needs clinician" },
  actionOptions: { call_again: "Call again", clinic_visit: "Clinic visit", urgent_review: "Urgent review", none: "None" },
};

const followUpBangla = {
  ...followUpEnglish,
  back: "বাতিল",
  eyebrow: "সিএইচডব্লিউ ফলো-আপ",
  title: (id: string) => `${id}-এর সঙ্গে কী হয়েছে?`,
  subtitle: "রেকর্ডটি সংক্ষিপ্ত, গোছানো এবং পরবর্তী কাজকেন্দ্রিক রাখুন।",
  restored: "এই ডিভাইস থেকে খসড়া ফিরিয়ে আনা হয়েছে।",
  contactMethod: "যোগাযোগের পদ্ধতি",
  outcome: "ফলাফল",
  note: "সংক্ষিপ্ত নোট",
  noteLabel: "ফলো-আপ নোট",
  notePlaceholder: "উদাহরণ: মায়ের সঙ্গে কথা হয়েছে; ক্লিনিক ভিজিট নিশ্চিত",
  noteRequired: "যোগাযোগের বিষয়ে একটি ছোট নোট লিখুন।",
  noteHelper: "সিঙ্ক না হওয়া পর্যন্ত এই নোট ডিভাইসেই থাকবে।",
  nextAction: "পরবর্তী কাজ",
  save: "ফলো-আপ সংরক্ষণ করুন",
  saveLabel: "ফলো-আপ সংরক্ষণ করুন",
  savedTitle: "ফলো-আপ সংরক্ষিত হয়েছে",
  savedBody: "সম্পন্ন যোগাযোগটি এই ডিভাইসে সংরক্ষিত এবং সিঙ্কের জন্য প্রস্তুত।",
  done: "সম্পন্ন",
  saveErrorTitle: "ফলো-আপ সংরক্ষণ করা যায়নি",
  saveErrorBody: "রেকর্ডটি অপরিবর্তিত আছে। লোকাল স্টোরেজ পরীক্ষা করে আবার চেষ্টা করুন।",
  pickPersonTitle: "কার সঙ্গে যোগাযোগ হয়েছে?",
  pickPersonBody: "আজকের কিউ থেকে একজন নারী বেছে নিন, তারপর কী হয়েছে লিখুন।",
  contactOptions: { visit: "ভিজিট", phone: "ফোন", sms: "এসএমএস" },
  outcomeOptions: { reached: "যোগাযোগ হয়েছে", no_answer: "উত্তর নেই", needs_clinician: "চিকিৎসকের সাহায্য দরকার" },
  actionOptions: { call_again: "আবার কল", clinic_visit: "ক্লিনিক ভিজিট", urgent_review: "জরুরি পর্যালোচনা", none: "কোনোটি নয়" },
};

const followUpHindi = {
  ...followUpEnglish,
  back: "रद्द करें",
  eyebrow: "सीएचडब्ल्यू फॉलो-अप",
  title: (id: string) => `${id} के साथ क्या हुआ?`,
  subtitle: "रिकॉर्ड को छोटा, व्यवस्थित और अगले कदम पर केंद्रित रखें।",
  restored: "इस डिवाइस से ड्राफ्ट वापस लाया गया है।",
  contactMethod: "संपर्क का तरीका",
  outcome: "परिणाम",
  note: "छोटा नोट",
  noteLabel: "फॉलो-अप नोट",
  notePlaceholder: "उदाहरण: माँ से बात हुई; क्लिनिक विज़िट की पुष्टि हुई",
  noteRequired: "संपर्क के बारे में छोटा नोट लिखें।",
  noteHelper: "सिंक उपलब्ध होने तक यह नोट डिवाइस पर रहेगा।",
  nextAction: "अगला कदम",
  save: "फॉलो-अप सहेजें",
  saveLabel: "फॉलो-अप सहेजें",
  savedTitle: "फॉलो-अप सहेजा गया",
  savedBody: "पूरा संपर्क इस डिवाइस पर सहेजा गया है और सिंक के लिए तैयार है।",
  done: "हो गया",
  saveErrorTitle: "फॉलो-अप सहेजा नहीं जा सका",
  saveErrorBody: "रिकॉर्ड में बदलाव नहीं हुआ। लोकल स्टोरेज जाँचकर फिर कोशिश करें।",
  pickPersonTitle: "आपने किससे संपर्क किया?",
  pickPersonBody: "आज की क्यू से एक महिला चुनें, फिर क्या हुआ लिखें।",
  contactOptions: { visit: "भेंट", phone: "फोन", sms: "एसएमएस" },
  outcomeOptions: { reached: "संपर्क हुआ", no_answer: "उत्तर नहीं मिला", needs_clinician: "चिकित्सक की जरूरत" },
  actionOptions: { call_again: "फिर कॉल करें", clinic_visit: "क्लिनिक भेंट", urgent_review: "तत्काल समीक्षा", none: "कोई नहीं" },
};

const followUpUrdu = {
  ...followUpEnglish,
  back: "منسوخ کریں",
  eyebrow: "سی ایچ ڈبلیو فالو اَپ",
  title: (id: string) => `${id} کے ساتھ کیا ہوا؟`,
  subtitle: "ریکارڈ مختصر، منظم اور اگلے قدم پر مرکوز رکھیں۔",
  restored: "اس ڈیوائس سے ڈرافٹ واپس لایا گیا ہے۔",
  contactMethod: "رابطے کا طریقہ",
  outcome: "نتیجہ",
  note: "مختصر نوٹ",
  noteLabel: "فالو اَپ نوٹ",
  notePlaceholder: "مثال: والدہ سے بات ہوئی؛ کلینک وزٹ کی تصدیق ہوئی",
  noteRequired: "رابطے کے بارے میں مختصر نوٹ لکھیں۔",
  noteHelper: "ہم وقت ہونے تک یہ نوٹ ڈیوائس پر رہے گا۔",
  nextAction: "اگلا قدم",
  save: "فالو اَپ محفوظ کریں",
  saveLabel: "فالو اَپ محفوظ کریں",
  savedTitle: "فالو اَپ محفوظ ہو گیا",
  savedBody: "مکمل رابطہ اس ڈیوائس پر محفوظ ہے اور ہم وقت ہونے کے لیے تیار ہے۔",
  done: "مکمل",
  saveErrorTitle: "فالو اَپ محفوظ نہیں ہو سکا",
  saveErrorBody: "ریکارڈ تبدیل نہیں ہوا۔ مقامی اسٹوریج چیک کرکے دوبارہ کوشش کریں۔",
  pickPersonTitle: "آپ نے کس سے رابطہ کیا؟",
  pickPersonBody: "آج کی قطار سے ایک خاتون چنیں، پھر کیا ہوا درج کریں۔",
  contactOptions: { visit: "ملاقات", phone: "فون", sms: "ایس ایم ایس" },
  outcomeOptions: { reached: "رابطہ ہوا", no_answer: "جواب نہیں ملا", needs_clinician: "طبیب کی ضرورت" },
  actionOptions: { call_again: "دوبارہ کال", clinic_visit: "کلینک وزٹ", urgent_review: "فوری جائزہ", none: "کوئی نہیں" },
};

const followUpCopyByLanguage: Partial<Record<AppLanguage, typeof followUpEnglish>> = { bn: followUpBangla, en: followUpEnglish, hi: followUpHindi, ur: followUpUrdu };

export function getFollowUpCopy(language: AppLanguage) {
  return followUpCopyByLanguage[language] ?? followUpEnglish;
}

const settingsEnglish = {
  eyebrow: "SETTINGS",
  subtitle: "Keep Call Aunty helpful, private, and easy to reach.",
  profileMeta: "Woman · Bangla preferred",
  profileNameWoman: "Aisha Rahman",
  profileNameChw: "Salma Khatun",
  profileMetaChw: "Community health worker",
  roleSection: "Who is using this phone",
  calleAgentTitle: "CALL-E phone agent",
  calleAgentDetail: "Place an authorized server-side follow-up call",
  reachSection: "How Aunty reaches you",
  safeWindow: "6:00 PM – 8:00 PM",
  safeWindowAlertTitle: "Safe contact window",
  safeWindowAlertBody: "You can update this preference before your next call.",
  sharedPhoneDetail: "Neutral greetings on",
  autoLockAfter: "after backgrounding",
  passcodeConfigured: "Configured · tap to change",
  passcodeMissing: "Set a 4–6 digit fallback",
  securityAutoLock: "auto-lock",
  remindersAlertTitle: "Reminders",
  remindersAlertBody: "Reminder preferences can be updated here.",
  privacyAlertTitle: "Privacy",
  privacyAlertBody: "Call Aunty only collects information needed for your care workflow. Clinical decisions remain with health professionals.",
  languageSaveErrorTitle: "Could not save language",
  languageSaveErrorBody: "Your current language will remain active for this session.",
  timeoutSaveErrorTitle: "Could not save timeout",
  timeoutSaveErrorBody: "The previous lock timeout remains active.",
  pickerTitle: "Choose language",
  pickerSubtitle: "Translations work offline and can be changed at any time.",
  selected: "Selected",
  cancel: "Cancel",
  passcodeMismatch: "Current passcode did not match.",
  passcodeLength: "Passcode must be 4 to 6 digits.",
  passcodeConfirmMismatch: "Passcodes did not match. Try again.",
  passcodeSaveError: "Could not save the passcode. Your previous protection remains active.",
  verifyCurrent: "Verify current passcode",
  confirmNew: "Confirm new passcode",
  resetFallback: "Reset passcode fallback",
  setFallback: "Set passcode fallback",
  verifyBeforeChange: "Verify before changing your fallback.",
  enterAgain: "Enter the same digits again to confirm.",
  verifyBeforeClear: "Verify your current passcode before clearing it.",
  reset: "Reset",
  continue: "Continue",
  savePasscode: "Save passcode",
};

const settingsBangla = {
  ...settingsEnglish,
  eyebrow: "সেটিংস",
  subtitle: "কল আন্টিকে সহায়ক, ব্যক্তিগত এবং সহজে ব্যবহারের উপযোগী রাখুন।",
  profileMeta: "নারী · বাংলা পছন্দ",
  profileNameWoman: "আয়েশা রহমান",
  profileNameChw: "সালমা খাতুন",
  profileMetaChw: "কমিউনিটি স্বাস্থ্যকর্মী",
  roleSection: "এই ফোন কে ব্যবহার করছেন",
  calleAgentTitle: "CALL-E ফোন এজেন্ট",
  calleAgentDetail: "অনুমোদিত সার্ভার-সাইড ফলো-আপ কল করুন",
  reachSection: "আন্টি কীভাবে যোগাযোগ করবেন",
  safeWindow: "সন্ধ্যা ৬টা – রাত ৮টা",
  safeWindowAlertTitle: "নিরাপদ যোগাযোগের সময়",
  safeWindowAlertBody: "পরবর্তী কলের আগে এই পছন্দ পরিবর্তন করতে পারেন।",
  sharedPhoneDetail: "নিরপেক্ষ শুভেচ্ছা চালু",
  autoLockAfter: "ব্যাকগ্রাউন্ডে যাওয়ার পর",
  passcodeConfigured: "সেট করা আছে · বদলাতে চাপুন",
  passcodeMissing: "৪–৬ সংখ্যার ব্যাকআপ সেট করুন",
  securityAutoLock: "অটো-লক",
  remindersAlertTitle: "মনে করিয়ে দেওয়া",
  remindersAlertBody: "রিমাইন্ডারের পছন্দ এখানে পরিবর্তন করা যাবে।",
  privacyAlertTitle: "গোপনীয়তা",
  privacyAlertBody: "কল আন্টি আপনার যত্নের কাজের জন্য প্রয়োজনীয় তথ্যই সংগ্রহ করে। চিকিৎসার সিদ্ধান্ত স্বাস্থ্য পেশাজীবীরা নেন।",
  languageSaveErrorTitle: "ভাষা সংরক্ষণ করা যায়নি",
  languageSaveErrorBody: "এই সেশনে আপনার বর্তমান ভাষাই চালু থাকবে।",
  timeoutSaveErrorTitle: "সময়সীমা সংরক্ষণ করা যায়নি",
  timeoutSaveErrorBody: "আগের লক সময়সীমাই চালু থাকবে।",
  pickerTitle: "ভাষা বেছে নিন",
  pickerSubtitle: "অনুবাদ অফলাইনে কাজ করে এবং যেকোনো সময় পরিবর্তন করা যায়।",
  selected: "নির্বাচিত",
  cancel: "বাতিল",
  passcodeMismatch: "বর্তমান পাসকোড মেলেনি।",
  passcodeLength: "পাসকোড ৪ থেকে ৬ সংখ্যার হতে হবে।",
  passcodeConfirmMismatch: "পাসকোড মেলেনি। আবার চেষ্টা করুন।",
  passcodeSaveError: "পাসকোড সংরক্ষণ করা যায়নি। আগের সুরক্ষা চালু আছে।",
  verifyCurrent: "বর্তমান পাসকোড যাচাই করুন",
  confirmNew: "নতুন পাসকোড নিশ্চিত করুন",
  resetFallback: "পাসকোড ব্যাকআপ রিসেট করুন",
  setFallback: "পাসকোড ব্যাকআপ সেট করুন",
  verifyBeforeChange: "ব্যাকআপ বদলানোর আগে যাচাই করুন।",
  enterAgain: "নিশ্চিত করতে একই সংখ্যা আবার লিখুন।",
  verifyBeforeClear: "মুছে ফেলার আগে বর্তমান পাসকোড যাচাই করুন।",
  reset: "রিসেট",
  continue: "চালিয়ে যান",
  savePasscode: "পাসকোড সংরক্ষণ করুন",
};

const settingsHindi = {
  ...settingsEnglish,
  eyebrow: "सेटिंग्स",
  subtitle: "कॉल आंटी को उपयोगी, निजी और आसानी से उपलब्ध रखें।",
  profileMeta: "महिला · हिन्दी पसंद",
  profileNameWoman: "आयशा रहमान",
  profileNameChw: "सलमा खातून",
  profileMetaChw: "सामुदायिक स्वास्थ्यकर्मी",
  roleSection: "यह फ़ोन कौन इस्तेमाल कर रहा है",
  calleAgentTitle: "CALL-E फ़ोन एजेंट",
  calleAgentDetail: "अधिकृत सर्वर-साइड फॉलो-अप कॉल करें",
  reachSection: "आंटी आप तक कैसे पहुँचती हैं",
  safeWindow: "शाम ६:०० – ८:०० बजे",
  sharedPhoneDetail: "तटस्थ अभिवादन चालू",
  passcodeConfigured: "सेट है · बदलने के लिए टैप करें",
  passcodeMissing: "४–६ अंकों का बैकअप सेट करें",
  pickerTitle: "भाषा चुनें",
  pickerSubtitle: "अनुवाद ऑफलाइन काम करते हैं और कभी भी बदले जा सकते हैं।",
  selected: "चयनित",
  cancel: "रद्द करें",
  passcodeMismatch: "वर्तमान पासकोड मेल नहीं खाता।",
  passcodeLength: "पासकोड ४ से ६ अंकों का होना चाहिए।",
  passcodeConfirmMismatch: "पासकोड मेल नहीं खाते। फिर कोशिश करें।",
  verifyCurrent: "वर्तमान पासकोड सत्यापित करें",
  confirmNew: "नया पासकोड पक्का करें",
  resetFallback: "पासकोड बैकअप रीसेट करें",
  setFallback: "पासकोड बैकअप सेट करें",
  verifyBeforeChange: "बैकअप बदलने से पहले सत्यापित करें।",
  enterAgain: "पुष्टि के लिए वही अंक फिर दर्ज करें।",
  verifyBeforeClear: "हटाने से पहले वर्तमान पासकोड सत्यापित करें।",
  reset: "रीसेट",
  continue: "जारी रखें",
  savePasscode: "पासकोड सहेजें",
};

const settingsUrdu = {
  ...settingsEnglish,
  eyebrow: "ترتیبات",
  subtitle: "کال آنٹی کو مددگار، نجی اور آسان رسائی والا رکھیں۔",
  profileMeta: "خاتون · اردو پسند",
  profileNameWoman: "عائشہ رحمان",
  profileNameChw: "سلمیٰ خاتون",
  profileMetaChw: "کمیونٹی صحت کارکن",
  roleSection: "یہ فون کون استعمال کر رہا ہے",
  calleAgentTitle: "CALL-E فون ایجنٹ",
  calleAgentDetail: "مجاز سرور سائیڈ فالو اَپ کال کریں",
  reachSection: "آنٹی آپ تک کیسے پہنچیں گی",
  safeWindow: "شام ۶:۰۰ – ۸:۰۰ بجے",
  sharedPhoneDetail: "غیر جانب دار سلام فعال",
  passcodeConfigured: "سیٹ ہے · تبدیل کرنے کے لیے دبائیں",
  passcodeMissing: "۴–۶ ہندسوں کا بیک اپ سیٹ کریں",
  pickerTitle: "زبان منتخب کریں",
  pickerSubtitle: "ترجمے آف لائن کام کرتے ہیں اور کسی بھی وقت بدلے جا سکتے ہیں۔",
  privacyAlertTitle: "رازداری",
  selected: "منتخب",
  cancel: "منسوخ",
  passcodeMismatch: "موجودہ پاس کوڈ مماثل نہیں۔",
  passcodeLength: "پاس کوڈ ۴ سے ۶ ہندسوں کا ہونا چاہیے۔",
  passcodeConfirmMismatch: "پاس کوڈ مماثل نہیں۔ دوبارہ کوشش کریں۔",
  verifyCurrent: "موجودہ پاس کوڈ کی تصدیق کریں",
  confirmNew: "نئے پاس کوڈ کی تصدیق کریں",
  resetFallback: "پاس کوڈ بیک اپ ری سیٹ کریں",
  setFallback: "پاس کوڈ بیک اپ سیٹ کریں",
  verifyBeforeChange: "بیک اپ تبدیل کرنے سے پہلے تصدیق کریں۔",
  enterAgain: "تصدیق کے لیے وہی ہندسے دوبارہ درج کریں۔",
  verifyBeforeClear: "صاف کرنے سے پہلے موجودہ پاس کوڈ کی تصدیق کریں۔",
  reset: "ری سیٹ",
  continue: "جاری رکھیں",
  savePasscode: "پاس کوڈ محفوظ کریں",
};

const settingsCopyByLanguage: Partial<Record<AppLanguage, typeof settingsEnglish>> = { bn: settingsBangla, en: settingsEnglish, hi: settingsHindi, ur: settingsUrdu };

export function getSettingsCopy(language: AppLanguage) {
  return settingsCopyByLanguage[language] ?? settingsEnglish;
}

const sharedEnglish = {
  callHandoffTitle: "Call handoff",
  callHandoffBody: "Your call handoff is ready.",
  genericErrorTitle: "Something went wrong",
  genericErrorBody: "Your local record is unchanged. Please try again.",
  privacyRecoveryBody: "Your protected records remain unchanged. Unlock the privacy lock and try again.",
  communityClinic: "Salma · Community clinic",
  close: "Close",
};

const sharedBangla = {
  ...sharedEnglish,
  callHandoffTitle: "কল হ্যান্ডঅফ",
  callHandoffBody: "আপনার কল হ্যান্ডঅফ প্রস্তুত।",
  genericErrorTitle: "সমস্যা হয়েছে",
  genericErrorBody: "আপনার লোকাল রেকর্ড অপরিবর্তিত আছে। আবার চেষ্টা করুন।",
  privacyRecoveryBody: "আপনার সুরক্ষিত রেকর্ড অপরিবর্তিত আছে। প্রাইভেসি লক খুলে আবার চেষ্টা করুন।",
  communityClinic: "সালমা · কমিউনিটি ক্লিনিক",
  close: "বন্ধ করুন",
};

const sharedHindi = {
  ...sharedEnglish,
  callHandoffTitle: "कॉल हैंडऑफ",
  callHandoffBody: "आपका कॉल हैंडऑफ तैयार है।",
  genericErrorTitle: "कुछ गलत हुआ",
  genericErrorBody: "आपका लोकल रिकॉर्ड अपरिवर्तित है। फिर कोशिश करें।",
  privacyRecoveryBody: "आपके सुरक्षित रिकॉर्ड अपरिवर्तित हैं। प्राइवेसी लॉक खोलकर फिर कोशिश करें।",
  communityClinic: "सलमा · सामुदायिक क्लिनिक",
  close: "बंद करें",
};

const sharedUrdu = {
  ...sharedEnglish,
  callHandoffTitle: "کال ہینڈ آف",
  callHandoffBody: "آپ کا کال ہینڈ آف تیار ہے۔",
  genericErrorTitle: "کچھ غلط ہو گیا",
  genericErrorBody: "آپ کا مقامی ریکارڈ تبدیل نہیں ہوا۔ دوبارہ کوشش کریں۔",
  privacyRecoveryBody: "آپ کے محفوظ ریکارڈ تبدیل نہیں ہوئے۔ پرائیویسی لاک کھول کر دوبارہ کوشش کریں۔",
  communityClinic: "سلمیٰ · کمیونٹی کلینک",
  close: "بند کریں",
};

const sharedCopyByLanguage: Partial<Record<AppLanguage, typeof sharedEnglish>> = { bn: sharedBangla, en: sharedEnglish, hi: sharedHindi, ur: sharedUrdu };

export function getSharedCopy(language: AppLanguage) {
  return sharedCopyByLanguage[language] ?? sharedEnglish;
}

export type CarePlanCardCopy = { title: string; meta: string; state: string; accessibilitySummary: string };

const carePlanCardsByLanguage: Partial<Record<AppLanguage, CarePlanCardCopy[]>> = {
  en: [
    { title: "ANC visit · 26 weeks", meta: "Due in 12 days · Community clinic", state: "Upcoming", accessibilitySummary: "ANC visit due in 12 days at the community clinic." },
    { title: "Iron and folic acid", meta: "Take as advised by your health worker", state: "Routine", accessibilitySummary: "Routine iron and folic acid reminder." },
    { title: "Post-visit check-in", meta: "Aunty will call after your clinic visit", state: "Scheduled", accessibilitySummary: "Scheduled check-in after the clinic visit." },
  ],
  bn: [
    { title: "এএনসি ভিজিট · ২৬ সপ্তাহ", meta: "১২ দিনের মধ্যে · কমিউনিটি ক্লিনিক", state: "আসন্ন", accessibilitySummary: "কমিউনিটি ক্লিনিকে ১২ দিনের মধ্যে এএনসি ভিজিট।" },
    { title: "আয়রন ও ফলিক অ্যাসিড", meta: "স্বাস্থ্যকর্মীর পরামর্শ অনুযায়ী নিন", state: "নিয়মিত", accessibilitySummary: "নিয়মিত আয়রন ও ফলিক অ্যাসিডের মনে করিয়ে দেওয়া।" },
    { title: "ভিজিটের পর চেক-ইন", meta: "ক্লিনিক ভিজিটের পর আন্টি কল করবেন", state: "নির্ধারিত", accessibilitySummary: "ক্লিনিক ভিজিটের পর নির্ধারিত চেক-ইন।" },
  ],
  hi: [
    { title: "एएनसी विज़िट · २६ सप्ताह", meta: "१२ दिनों में · सामुदायिक क्लिनिक", state: "आगामी", accessibilitySummary: "सामुदायिक क्लिनिक में १२ दिनों में एएनसी विज़िट।" },
    { title: "आयरन और फोलिक एसिड", meta: "स्वास्थ्यकर्मी की सलाह के अनुसार लें", state: "नियमित", accessibilitySummary: "नियमित आयरन और फोलिक एसिड की याद।" },
    { title: "विज़िट के बाद चेक-इन", meta: "क्लिनिक विज़िट के बाद आंटी कॉल करेंगी", state: "निर्धारित", accessibilitySummary: "क्लिनिक विज़िट के बाद निर्धारित चेक-इन।" },
  ],
  ur: [
    { title: "اے این سی وزٹ · ۲۶ ہفتے", meta: "۱۲ دن میں · کمیونٹی کلینک", state: "آنے والا", accessibilitySummary: "کمیونٹی کلینک میں ۱۲ دن میں اے این سی وزٹ۔" },
    { title: "آئرن اور فولک ایسڈ", meta: "صحت کارکن کے مشورے کے مطابق لیں", state: "معمول", accessibilitySummary: "آئرن اور فولک ایسڈ کی معمول کی یاد دہانی۔" },
    { title: "وزٹ کے بعد چیک اِن", meta: "کلینک وزٹ کے بعد آنٹی کال کریں گی", state: "مقررہ", accessibilitySummary: "کلینک وزٹ کے بعد مقررہ چیک اِن۔" },
  ],
};

export function getCarePlanCards(language: AppLanguage): CarePlanCardCopy[] {
  return carePlanCardsByLanguage[language] ?? carePlanCardsByLanguage.en!;
}

export type WomanDashboardAccessibilityCopy = {
  startCheckIn: string;
  carePlanCard: string;
  carePlanOpen: string;
  callAunty: string;
  callAuntyHint: string;
};

const womanDashboardAccessibilityByLanguage: Partial<Record<AppLanguage, WomanDashboardAccessibilityCopy>> = {
  en: {
    startCheckIn: "Start today’s check-in. About 2 minutes. You can pause.",
    carePlanCard: "Open the ANC visit care-plan item due in 12 days at the community clinic.",
    carePlanOpen: "Open the full care plan.",
    callAunty: "Call Aunty.",
    callAuntyHint: "The greeting stays neutral until it is safe to continue.",
  },
  bn: {
    startCheckIn: "আজকের চেক-ইন শুরু করুন। প্রায় ২ মিনিট। চাইলে বিরতি নিতে পারেন।",
    carePlanCard: "১২ দিনের মধ্যে কমিউনিটি ক্লিনিকে এএনসি ভিজিটের যত্নের কাজ খুলুন।",
    carePlanOpen: "সম্পূর্ণ যত্নের পরিকল্পনা খুলুন।",
    callAunty: "কল আন্টি।",
    callAuntyHint: "নিরাপদে চালিয়ে যাওয়া নিশ্চিত না হওয়া পর্যন্ত শুভেচ্ছা নিরপেক্ষ থাকবে।",
  },
  hi: {
    startCheckIn: "आज का चेक-इन शुरू करें। लगभग २ मिनट। आप रोक सकती हैं।",
    carePlanCard: "१२ दिनों में सामुदायिक क्लिनिक में होने वाली एएनसी विज़िट का देखभाल आइटम खोलें।",
    carePlanOpen: "पूरी देखभाल योजना खोलें।",
    callAunty: "आंटी को कॉल करें।",
    callAuntyHint: "सुरक्षित होने तक अभिवादन तटस्थ रहेगा।",
  },
  ur: {
    startCheckIn: "آج کا چیک اِن شروع کریں۔ تقریباً ۲ منٹ۔ آپ روک سکتی ہیں۔",
    carePlanCard: "۱۲ دن میں کمیونٹی کلینک کے اے این سی وزٹ کا دیکھ بھال کا کام کھولیں۔",
    carePlanOpen: "مکمل دیکھ بھال کا منصوبہ کھولیں۔",
    callAunty: "آنٹی کو کال کریں۔",
    callAuntyHint: "محفوظ ہونے تک سلام غیر جانب دار رہے گا۔",
  },
};

export function getWomanDashboardAccessibilityCopy(language: AppLanguage): WomanDashboardAccessibilityCopy {
  return womanDashboardAccessibilityByLanguage[language] ?? womanDashboardAccessibilityByLanguage.en!;
}

export type ChwDashboardAccessibilityCopy = {
  hero: string;
  refreshQueue: string;
  syncDiagnostic: string;
  lockOn: string;
  lockOff: string;
  newFollowUp: string;
  openQueueRecord: string;
};

const chwDashboardAccessibilityByLanguage: Partial<Record<AppLanguage, ChwDashboardAccessibilityCopy>> = {
  en: {
    hero: "Field queue with 3 prioritized actions. One urgent case needs attention today.",
    refreshQueue: "Refresh the prioritized follow-up queue.",
    syncDiagnostic: "Check internet reachability and sync queue status.",
    lockOn: "Privacy lock is on. Protected records are unavailable until unlocked.",
    lockOff: "Privacy lock is off. Tap to protect sensitive records.",
    newFollowUp: "Capture a new follow-up and save it offline.",
    openQueueRecord: "Open this woman’s follow-up record.",
  },
  bn: {
    hero: "ফিল্ড কিউতে ৩টি অগ্রাধিকার কাজ। আজ একটি জরুরি কেসে মনোযোগ দরকার।",
    refreshQueue: "অগ্রাধিকার ফলো-আপ কিউ রিফ্রেশ করুন।",
    syncDiagnostic: "ইন্টারনেট সংযোগ ও সিঙ্ক কিউয়ের অবস্থা পরীক্ষা করুন।",
    lockOn: "প্রাইভেসি লক চালু আছে। আনলক না করা পর্যন্ত সুরক্ষিত রেকর্ড দেখা যাবে না।",
    lockOff: "প্রাইভেসি লক বন্ধ আছে। সংবেদনশীল রেকর্ড সুরক্ষিত করতে চাপুন।",
    newFollowUp: "নতুন ফলো-আপ নিন এবং অফলাইনে সংরক্ষণ করুন।",
    openQueueRecord: "এই নারীর ফলো-আপ রেকর্ড খুলুন।",
  },
  hi: {
    hero: "फील्ड क्यू में ३ प्राथमिक कार्य हैं। आज एक जरूरी मामले पर ध्यान चाहिए।",
    refreshQueue: "प्राथमिक फॉलो-अप क्यू को रीफ्रेश करें।",
    syncDiagnostic: "इंटरनेट पहुंच और सिंक क्यू की स्थिति जांचें।",
    lockOn: "प्राइवेसी लॉक चालू है। अनलॉक होने तक सुरक्षित रिकॉर्ड उपलब्ध नहीं हैं।",
    lockOff: "प्राइवेसी लॉक बंद है। संवेदनशील रिकॉर्ड सुरक्षित करने के लिए दबाएं।",
    newFollowUp: "नया फॉलो-अप दर्ज करें और ऑफलाइन सहेजें।",
    openQueueRecord: "इस महिला का फॉलो-अप रिकॉर्ड खोलें।",
  },
  ur: {
    hero: "فیلڈ کیو میں ۳ ترجیحی کام ہیں۔ آج ایک فوری کیس پر توجہ درکار ہے۔",
    refreshQueue: "ترجیحی فالو اَپ کیو تازہ کریں۔",
    syncDiagnostic: "انٹرنیٹ اور ہم وقت سازی کیو کی حالت چیک کریں۔",
    lockOn: "پرائیویسی لاک آن ہے۔ ان لاک ہونے تک محفوظ ریکارڈ دستیاب نہیں۔",
    lockOff: "پرائیویسی لاک آف ہے۔ حساس ریکارڈ محفوظ کرنے کے لیے دبائیں۔",
    newFollowUp: "نیا فالو اَپ درج کریں اور آف لائن محفوظ کریں۔",
    openQueueRecord: "اس خاتون کا فالو اَپ ریکارڈ کھولیں۔",
  },
};

export function getChwDashboardAccessibilityCopy(language: AppLanguage): ChwDashboardAccessibilityCopy {
  return chwDashboardAccessibilityByLanguage[language] ?? chwDashboardAccessibilityByLanguage.en!;
}

export type ChwSyncAccessibilityCopy = {
  resultLabel: string;
  fallbackResult: string;
  preservedResult: string;
  retryHint: string;
  conflictResult: string;
};

const chwSyncAccessibilityByLanguage: Partial<Record<AppLanguage, ChwSyncAccessibilityCopy>> = {
  en: {
    resultLabel: "Sync result",
    fallbackResult: "Sync is unavailable. Local work remains protected on this device.",
    preservedResult: "Newer local work was preserved for review.",
    retryHint: "Retry the queued follow-up when connectivity is available.",
    conflictResult: "The conflict decision was saved locally.",
  },
  bn: {
    resultLabel: "সিঙ্কের ফলাফল",
    fallbackResult: "সিঙ্ক এখন সম্ভব নয়। লোকাল কাজ এই ডিভাইসে সুরক্ষিত আছে।",
    preservedResult: "নতুন লোকাল কাজ পর্যালোচনার জন্য রাখা হয়েছে।",
    retryHint: "সংযোগ পাওয়া গেলে কিউয়ের ফলো-আপ আবার চেষ্টা করুন।",
    conflictResult: "দ্বন্দ্বের সিদ্ধান্ত লোকালি সংরক্ষিত হয়েছে।",
  },
  hi: {
    resultLabel: "सिंक परिणाम",
    fallbackResult: "सिंक उपलब्ध नहीं है। लोकल काम इस डिवाइस पर सुरक्षित है।",
    preservedResult: "नया लोकल काम समीक्षा के लिए सुरक्षित रखा गया है।",
    retryHint: "कनेक्शन मिलने पर कतारबद्ध फॉलो-अप फिर कोशिश करें।",
    conflictResult: "संघर्ष का निर्णय लोकल रूप से सहेजा गया है।",
  },
  ur: {
    resultLabel: "ہم وقت سازی کا نتیجہ",
    fallbackResult: "ہم وقت سازی دستیاب نہیں۔ مقامی کام اس ڈیوائس پر محفوظ ہے۔",
    preservedResult: "نیا مقامی کام جائزے کے لیے محفوظ رکھا گیا ہے۔",
    retryHint: "کنکشن دستیاب ہونے پر قطار والے فالو اَپ کی دوبارہ کوشش کریں۔",
    conflictResult: "تنازع کا فیصلہ مقامی طور پر محفوظ ہو گیا ہے۔",
  },
};

export function getChwSyncAccessibilityCopy(language: AppLanguage): ChwSyncAccessibilityCopy {
  return chwSyncAccessibilityByLanguage[language] ?? chwSyncAccessibilityByLanguage.en!;
}
