import type { AppLanguage } from "@/lib/language";

type OfflineDataCopy = { label: string; detail: string; title: string; body: string; clear: string; cancel: string; success: string; error: string; locked: string };

const copyByLanguage: Record<AppLanguage, OfflineDataCopy> = {
  en: { label: "Clear offline data", detail: "Remove saved check-ins and queued sync records", title: "Clear offline data?", body: "This removes local check-in progress, saved care-plan metadata, and queued sync records from this device.", clear: "Clear", cancel: "Cancel", success: "Offline data cleared from this device.", error: "Could not clear every offline item. Your remaining local data is protected.", locked: "Unlock privacy protection before clearing sensitive offline data." },
  bn: { label: "অফলাইন ডেটা মুছুন", detail: "সংরক্ষিত চেক-ইন ও সিঙ্কের অপেক্ষার রেকর্ড মুছুন", title: "অফলাইন ডেটা মুছবেন?", body: "এই ডিভাইস থেকে লোকাল চেক-ইন অগ্রগতি, যত্নের পরিকল্পনার মেটাডেটা ও সিঙ্কের অপেক্ষার রেকর্ড মুছে যাবে।", clear: "মুছুন", cancel: "বাতিল", success: "এই ডিভাইস থেকে অফলাইন ডেটা মুছে ফেলা হয়েছে।", error: "সব অফলাইন ডেটা মুছতে পারিনি। বাকি লোকাল ডেটা সুরক্ষিত আছে।", locked: "সংবেদনশীল অফলাইন ডেটা মুছতে আগে গোপনীয়তা লক খুলুন।" },
  hi: { label: "ऑफलाइन डेटा साफ करें", detail: "सहेजे गए चेक-इन और कतार रिकॉर्ड हटाएं", title: "ऑफलाइन डेटा साफ करें?", body: "इस डिवाइस से लोकल चेक-इन प्रगति, देखभाल योजना मेटाडेटा और कतार में रखे सिंक रिकॉर्ड हट जाएंगे।", clear: "साफ करें", cancel: "रद्द करें", success: "इस डिवाइस से ऑफलाइन डेटा साफ कर दिया गया।", error: "सारा ऑफलाइन डेटा साफ नहीं हो सका। बचा हुआ लोकल डेटा सुरक्षित है।", locked: "संवेदनशील ऑफलाइन डेटा साफ करने से पहले प्राइवेसी लॉक खोलें।" },
  ur: { label: "آف لائن ڈیٹا صاف کریں", detail: "محفوظ چیک اِن اور قطار کے ریکارڈ ہٹائیں", title: "آف لائن ڈیٹا صاف کریں؟", body: "اس ڈیوائس سے مقامی چیک اِن پیش رفت، نگہداشت کے منصوبے کا میٹا ڈیٹا اور قطار میں موجود ہم وقت سازی کے ریکارڈ ہٹ جائیں گے۔", clear: "صاف کریں", cancel: "منسوخ", success: "اس ڈیوائس سے آف لائن ڈیٹا صاف ہو گیا۔", error: "تمام آف لائن ڈیٹا صاف نہیں ہو سکا۔ باقی مقامی ڈیٹا محفوظ ہے۔", locked: "حساس آف لائن ڈیٹا صاف کرنے سے پہلے پرائیویسی لاک کھولیں۔" },
  ta: { label: "ஆஃப்லைன் தரவை அழிக்கவும்", detail: "சேமித்த செக்-இன் மற்றும் வரிசை பதிவுகளை அகற்றவும்", title: "ஆஃப்லைன் தரவை அழிக்கவா?", body: "இந்த சாதனத்தில் உள்ளூர் செக்-இன் முன்னேற்றம், பராமரிப்பு திட்ட மெட்டாடேட்டா மற்றும் ஒத்திசைவு வரிசை பதிவுகள் அகற்றப்படும்.", clear: "அழிக்கவும்", cancel: "ரத்து", success: "இந்த சாதனத்திலிருந்து ஆஃப்லைன் தரவு அழிக்கப்பட்டது.", error: "அனைத்து ஆஃப்லைன் தரவையும் அழிக்க முடியவில்லை. மீதமுள்ள உள்ளூர் தரவு பாதுகாப்பாக உள்ளது.", locked: "முக்கியமான ஆஃப்லைன் தரவை அழிக்க தனியுரிமை பூட்டைத் திறக்கவும்." },
  te: { label: "ఆఫ్‌లైన్ డేటాను క్లియర్ చేయండి", detail: "సేవ్ చేసిన చెక్-ఇన్ మరియు క్యూ రికార్డులను తొలగించండి", title: "ఆఫ్‌లైన్ డేటాను క్లియర్ చేయాలా?", body: "ఈ పరికరంలోని స్థానిక చెక్-ఇన్ పురోగతి, సంరక్షణ ప్రణాళిక మెటాడేటా మరియు సింక్ క్యూ రికార్డులు తొలగించబడతాయి.", clear: "క్లియర్ చేయండి", cancel: "రద్దు", success: "ఈ పరికరం నుంచి ఆఫ్‌లైన్ డేటా క్లియర్ చేయబడింది.", error: "అన్ని ఆఫ్‌లైన్ డేటాను క్లియర్ చేయలేకపోయాం. మిగిలిన స్థానిక డేటా భద్రంగా ఉంది.", locked: "సున్నితమైన ఆఫ్‌లైన్ డేటాను క్లియర్ చేయడానికి గోప్యతా లాక్‌ను అన్‌లాక్ చేయండి." },
};

export function getOfflineDataCopy(language: AppLanguage): OfflineDataCopy {
  return copyByLanguage[language] ?? copyByLanguage.en;
}
