import { CALL_AUNTY_SURVEY } from "./survey";
import type { MockCallScenario } from "./types";

export const CALL_AUNTY_SCENARIOS: MockCallScenario[] = [
  {
    id: "aunty-complete-positive",
    title: "Completed survey — positive experience",
    purpose: "Happy-path transcript parsing and structured extraction.",
    respondentProfile: "Fictional respondent: Aunty Pat, retired teacher who recently used a community information service.",
    outcome: "completed",
    locale: "en",
    survey: CALL_AUNTY_SURVEY,
    transcript: [
      { speaker: "agent", text: "Hello, this is the Call Aunty research assistant. Am I speaking with Pat?", scriptKey: "greeting_named", scriptParams: { name: "Pat" } },
      { speaker: "aunty", text: "Yes, that is me." },
      { speaker: "agent", text: "Thanks. This is a fictional survey for testing. Is now a good time to answer a short survey, and may I record your answers for this survey?", questionId: "consent", scriptKey: "consent_prompt" },
      { speaker: "aunty", text: "Yes, that is fine.", questionId: "consent", answer: true },
      { speaker: "agent", text: "How would you describe your overall experience with the service?", questionId: "q01" },
      { speaker: "aunty", text: "Very positive.", questionId: "q01", answer: "Very positive" },
      { speaker: "agent", text: "On a scale from 1 to 5, how easy was it to get the help or information you needed?", questionId: "q02" },
      { speaker: "aunty", text: "Five. It was quite straightforward.", questionId: "q02", answer: 5 },
      { speaker: "agent", text: "How clear were the instructions you received, from 1 to 5?", questionId: "q03" },
      { speaker: "aunty", text: "Five again.", questionId: "q03", answer: 5 },
      { speaker: "agent", text: "What worked best for you?", questionId: "q05" },
      { speaker: "aunty", text: "The staff were helpful, the process was convenient, and the follow-up was good.", questionId: "q05", answer: ["Staff helpfulness", "Convenience", "Follow-up"] },
      { speaker: "agent", text: "Was there anything confusing or frustrating?", questionId: "q06" },
      { speaker: "aunty", text: "No, not really. I had to wait once, but it was not a big issue.", questionId: "q06", answer: "No major issue; there was one minor wait." },
      { speaker: "agent", text: "How likely are you to use the service again, from 0 to 10?", questionId: "q09" },
      { speaker: "aunty", text: "Nine.", questionId: "q09", answer: 9 },
      { speaker: "agent", text: "Anything important we did not ask about?", questionId: "q17" },
      { speaker: "aunty", text: "Just keep it simple. That helped me.", questionId: "q17", answer: "Keep the process simple." },
      { speaker: "agent", text: "May your comments be quoted anonymously in an internal summary?", questionId: "q20" },
      { speaker: "aunty", text: "Yes.", questionId: "q20", answer: true },
      { speaker: "agent", text: "Thank you, Pat. That completes the fictional survey.", scriptKey: "complete", scriptParams: { name: "Pat" } },
    ],
    extractedAnswers: {
      consent: true,
      q01: "Very positive",
      q02: 5,
      q03: 5,
      q05: ["Staff helpfulness", "Convenience", "Follow-up"],
      q06: "No major issue; there was one minor wait.",
      q09: 9,
      q17: "Keep the process simple.",
      q20: true,
    },
    assertions: [
      "Consent must be true before survey answers are persisted.",
      "Scale answers must normalize to numbers.",
      "Anonymous quote permission must be stored separately from raw contact data.",
    ],
  },
  {
    id: "aunty-complete-positive-bn",
    title: "Completed survey — Bangla script",
    purpose: "Same happy path spoken in Bangla, with canonical English structured answers.",
    respondentProfile: "Fictional respondent: Aunty Pat; prefers Bangla on the call.",
    outcome: "completed",
    locale: "bn",
    survey: CALL_AUNTY_SURVEY,
    transcript: [
      { speaker: "agent", text: "হ্যালো, আমি কল আন্টি গবেষণা সহকারী। আমি কি Pat-এর সঙ্গে কথা বলছি?", scriptKey: "greeting_named", scriptParams: { name: "Pat" } },
      { speaker: "aunty", text: "হ্যাঁ, আমিই।" },
      { speaker: "agent", text: "এটি পরীক্ষার জন্য একটি কাল্পনিক জরিপ। এখন কি একটি ছোট জরিপের উত্তর দেওয়ার ভালো সময়, এবং এই জরিপের জন্য আপনার উত্তর লিখে রাখতে পারি?", questionId: "consent", scriptKey: "consent_prompt" },
      { speaker: "aunty", text: "হ্যাঁ, ঠিক আছে।", questionId: "consent", answer: true },
      { speaker: "agent", text: "সেবার সঙ্গে আপনার সামগ্রিক অভিজ্ঞতা কেমন ছিল?", questionId: "q01" },
      { speaker: "aunty", text: "খুব ইতিবাচক।", questionId: "q01", answer: "Very positive" },
      { speaker: "agent", text: "১ থেকে ৫ স্কেলে, প্রয়োজনীয় সাহায্য বা তথ্য পাওয়া কতটা সহজ ছিল?", questionId: "q02" },
      { speaker: "aunty", text: "পাঁচ। সহজ ছিল।", questionId: "q02", answer: 5 },
      { speaker: "agent", text: "আপনি যে নির্দেশনা পেয়েছিলেন, তা কতটা পরিষ্কার ছিল?", questionId: "q03" },
      { speaker: "aunty", text: "আবার পাঁচ।", questionId: "q03", answer: 5 },
      { speaker: "agent", text: "অভিজ্ঞতার কোন অংশগুলো আপনার জন্য সবচেয়ে ভালো কাজ করেছে?", questionId: "q05" },
      { speaker: "aunty", text: "কর্মীরা সাহায্য করেছেন, প্রক্রিয়াটা সুবিধাজনক, ফলো-আপও ভালো।", questionId: "q05", answer: ["Staff helpfulness", "Convenience", "Follow-up"] },
      { speaker: "agent", text: "কিছু কি বিভ্রান্তিকর বা বিরক্তিকর ছিল?", questionId: "q06" },
      { speaker: "aunty", text: "না, তেমন না। একবার অপেক্ষা করতে হয়েছিল, বড় সমস্যা নয়।", questionId: "q06", answer: "No major issue; there was one minor wait." },
      { speaker: "agent", text: "০ থেকে ১০-এ, আবার এই সেবা ব্যবহার করার সম্ভাবনা কতটা?", questionId: "q09" },
      { speaker: "aunty", text: "নয়।", questionId: "q09", answer: 9 },
      { speaker: "agent", text: "এমন কিছু গুরুত্বপূর্ণ আছে যা আমরা জিজ্ঞাসা করিনি?", questionId: "q17" },
      { speaker: "aunty", text: "সহজ রাখুন। সেটাই সাহায্য করেছে।", questionId: "q17", answer: "Keep the process simple." },
      { speaker: "agent", text: "অভ্যন্তরীণ সারাংশে আপনার মন্তব্য কি বেনামে উদ্ধৃত করা যাবে?", questionId: "q20" },
      { speaker: "aunty", text: "হ্যাঁ।", questionId: "q20", answer: true },
      { speaker: "agent", text: "ধন্যবাদ, Pat। কাল্পনিক জরিপ এখানে শেষ।", scriptKey: "complete", scriptParams: { name: "Pat" } },
    ],
    extractedAnswers: {
      consent: true,
      q01: "Very positive",
      q02: 5,
      q03: 5,
      q05: ["Staff helpfulness", "Convenience", "Follow-up"],
      q06: "No major issue; there was one minor wait.",
      q09: 9,
      q17: "Keep the process simple.",
      q20: true,
    },
    assertions: [
      "Spoken Bangla must still extract canonical English option values.",
      "Consent must be true before survey answers are persisted.",
    ],
  },
  {
    id: "aunty-declines",
    title: "Declined survey",
    purpose: "Verify respectful refusal handling and zero-question collection.",
    respondentProfile: "Fictional respondent: Aunty May, busy during the initial call.",
    outcome: "declined",
    locale: "en",
    survey: CALL_AUNTY_SURVEY,
    transcript: [
      { speaker: "agent", text: "Hello, this is the Call Aunty research assistant. Is this May?", scriptKey: "greeting_named", scriptParams: { name: "May" } },
      { speaker: "aunty", text: "Yes." },
      { speaker: "agent", text: "This is a fictional survey for testing. Is now a good time to answer a short survey?", scriptKey: "consent_prompt", questionId: "consent" },
      { speaker: "aunty", text: "No, sorry. I am in the middle of something.", questionId: "consent", answer: false },
      { speaker: "agent", text: "No problem at all. I will not continue the survey. Thank you for your time.", scriptKey: "decline_close" },
    ],
    extractedAnswers: { consent: false },
    assertions: [
      "No survey question after consent may be asked.",
      "Declining must not be treated as a negative service rating.",
      "The call may end without collecting optional demographics.",
    ],
  },
  {
    id: "aunty-reschedule",
    title: "Requests a better time",
    purpose: "Exercise scheduling state and a clean handoff from the live call.",
    respondentProfile: "Fictional respondent: Aunty Jo, willing to participate later in the day.",
    outcome: "rescheduled",
    locale: "en",
    survey: CALL_AUNTY_SURVEY,
    transcript: [
      { speaker: "agent", text: "Hello Jo. I am calling with a short fictional survey. Is now a good time?", scriptKey: "greeting_generic" },
      { speaker: "aunty", text: "Not really. Could you call after dinner?" },
      { speaker: "agent", text: "Absolutely. I can mark this as a requested callback. Would 7:30 PM be suitable?", scriptKey: "reschedule_offer", scriptParams: { time: "7:30 PM" } },
      { speaker: "aunty", text: "Yes, that works." },
      { speaker: "system", text: "State transition: in_progress -> rescheduled; callback requested for 19:30 local time.", scriptKey: "system_reschedule", scriptParams: { time: "19:30" } },
    ],
    extractedAnswers: { consent: null },
    assertions: [
      "Do not infer consent merely because a callback was requested.",
      "Persist the scheduling intent without starting the survey.",
    ],
  },
  {
    id: "aunty-skip-question",
    title: "Consent granted, sensitive-adjacent question skipped",
    purpose: "Verify that skipping is allowed without pressure.",
    respondentProfile: "Fictional respondent: Aunty Rose, comfortable with service questions but not optional follow-up.",
    outcome: "completed",
    locale: "en",
    survey: CALL_AUNTY_SURVEY,
    transcript: [
      { speaker: "agent", text: "Hello Rose. This is a fictional survey test. May I ask a few short questions and record your answers for the survey?", questionId: "consent", scriptKey: "consent_prompt" },
      { speaker: "aunty", text: "Yes.", questionId: "consent", answer: true },
      { speaker: "agent", text: "Would you like someone to contact you about your feedback?", questionId: "q18" },
      { speaker: "aunty", text: "No, I would rather not be contacted.", questionId: "q18", answer: false },
      { speaker: "agent", text: "Understood. No follow-up contact will be requested.", questionId: "q18", scriptKey: "skip_no_followup" },
      { speaker: "agent", text: "May your comments be quoted anonymously in an internal summary?", questionId: "q20" },
      { speaker: "aunty", text: "Yes.", questionId: "q20", answer: true },
    ],
    extractedAnswers: { consent: true, q18: false, q20: true },
    assertions: [
      "q19 must remain unanswered because q18 is false.",
      "The agent must not ask for a phone number or email address after a no-follow-up answer.",
    ],
  },
  {
    id: "aunty-voicemail",
    title: "Voicemail — no survey started",
    purpose: "Ensure an automated voicemail path never fabricates consent or answers.",
    respondentProfile: "Fictional respondent: Aunty June; nobody answers the live call.",
    outcome: "voicemail",
    locale: "en",
    survey: CALL_AUNTY_SURVEY,
    transcript: [
      { speaker: "agent", text: "Hello, this is the Call Aunty research assistant. Please call back using the official callback channel if you would like to participate in the fictional survey. Goodbye.", scriptKey: "voicemail" },
      { speaker: "system", text: "Voicemail detected. Mark call as voicemail and do not initialize survey state.", scriptKey: "system_voicemail" },
    ],
    extractedAnswers: {},
    assertions: ["Consent is not assumed on voicemail.", "No survey response may be generated from a voicemail message."],
  },
  {
    id: "aunty-technical-failure",
    title: "Technical failure after consent",
    purpose: "Test resumable state and protection against duplicated questions after a transport interruption.",
    respondentProfile: "Fictional respondent: Aunty Sal, halfway through a survey when the call drops.",
    outcome: "technical_failure",
    locale: "en",
    survey: CALL_AUNTY_SURVEY,
    transcript: [
      { speaker: "agent", text: "This is a fictional survey for testing. May I record your answers?", questionId: "consent", scriptKey: "consent_prompt" },
      { speaker: "aunty", text: "Yes.", questionId: "consent", answer: true },
      { speaker: "agent", text: "How would you describe your overall experience?", questionId: "q01" },
      { speaker: "aunty", text: "Somewhat positive.", questionId: "q01", answer: "Somewhat positive" },
      { speaker: "agent", text: "How easy was it to get the help you needed, from 1 to 5?", questionId: "q02" },
      { speaker: "system", text: "Transport interruption. Persist cursor at q02 before retrying. Do not restart from consent.", scriptKey: "system_transport", scriptParams: { questionId: "q02" } },
    ],
    extractedAnswers: { consent: true, q01: "Somewhat positive" },
    assertions: [
      "Resume at the last unanswered question.",
      "Never issue a duplicate consent prompt solely because transport failed.",
      "Persist the run identifier before the call is retried.",
    ],
  },
  {
    id: "aunty-sensitive-distress",
    title: "Negative experience with safety-sensitive answer",
    purpose: "Branch away from NPS and probing after a distress cue; persist a code, not a quote.",
    respondentProfile: "Fictional respondent: Aunty Nila, reports a very negative day and asks not to discuss a safety concern.",
    outcome: "completed",
    locale: "en",
    escalation: "safety_script",
    survey: CALL_AUNTY_SURVEY,
    transcript: [
      { speaker: "agent", text: "Hello, this is the Call Aunty research assistant. Am I speaking with Nila?", scriptKey: "greeting_named", scriptParams: { name: "Nila" } },
      { speaker: "aunty", text: "Yes." },
      { speaker: "agent", text: "This is a fictional survey for testing. Is now a good time to answer a short survey, and may I record your answers for this survey?", questionId: "consent", scriptKey: "consent_prompt" },
      { speaker: "aunty", text: "Yes.", questionId: "consent", answer: true },
      { speaker: "agent", text: "How would you describe your overall experience with the service?", questionId: "q01" },
      { speaker: "aunty", text: "Very negative. It was a hard day.", questionId: "q01", answer: "Very negative" },
      { speaker: "agent", text: "Thank you for telling me. I will not ask you to rate or recommend the service. We can skip anything you do not want to answer.", scriptKey: "acknowledge_negative" },
      { speaker: "agent", text: "If you are willing, was there anything confusing or frustrating? You can skip this.", questionId: "q06", scriptKey: "q06_careful" },
      {
        speaker: "aunty",
        text: "I had severe pain and it was hard to breathe. Please do not ask me more about that.",
        questionId: "q06",
        answer: "safety_concern_reported",
      },
      { speaker: "agent", text: "I hear this may need in-person care. I will not ask more detail. Please seek urgent in-person care now. A health worker can follow up. I am stopping the remaining optional questions.", scriptKey: "safety_stop_probing" },
      { speaker: "system", text: "State: distress detected. Skip remaining optional questions. Persist a safety code, not a quotable narrative. Escalate to human follow-up.", scriptKey: "system_safety" },
    ],
    extractedAnswers: { consent: true, q01: "Very negative", q06: "safety_concern_reported" },
    assertions: [
      "q05, q09, q10, q15, q18, q19, and q20 must not be asked after distress.",
      "The agent must not probe for more clinical detail.",
      "Safety script must tell the person to seek in-person care.",
      "Do not collect contact PII after a distress stop.",
      "Persisted q06 must be a code, not the spoken clinical detail.",
    ],
  },
];

export function getCallAuntyScenario(id: string): MockCallScenario {
  const scenario = CALL_AUNTY_SCENARIOS.find((item) => item.id === id);
  if (!scenario) throw new Error(`Unknown Call Aunty scenario: ${id}`);
  return scenario;
}
